---
title: "R_analisis"
author: "Ismael Joaquín Borreguero Vázquez"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r paquetes, include=FALSE}
###se  cargan todos los paquetes
library(glmmTMB)
library(performance)
library(ggplot2)
library(readr)
library(itsadug)
library(data.table)
library(moments)
library(tidyverse)
library(readODS)
library(readxl)
library(patchwork)
library(lme4)
library(effects)
library(sjPlot)
library(lmerTest)
library(visreg)
library(car)
library(SPEI)
library(lmtest)
library(multcompView)
library(cowplot)
library(merTools)
library(plyr)
library(gamm4)
library(DHARMa)
library(MuMIn) ###para seleccionar modelo
source("Anatomy_function.R")
```

```{r datos, include=FALSE}
###clima
clima <- list()

clima$prp <- read_csv("Gamirprcp2019-2022.csv")

Temp_gamir_Nov20_Feb21 <- read_excel("Gamir_Nov20_Feb21.xlsx")
Temp_gamir_Feb21_Jun21 <- read_excel("Gamir_Feb21_Jun21.xlsx")
Temp_gamir_Jun21_May22 <- read_excel("Gamir_Jun21_May22.xlsx")
###le doy el formato de fecha
Temp_gamir_Feb21_Jun21$date <- as.Date( Temp_gamir_Feb21_Jun21$`Fecha/hora (CET)`, "%m/%d/%y")
Temp_gamir_Jun21_May22$date <- as.Date( Temp_gamir_Jun21_May22$`Fecha/hora (CET)`, "%y/%m/%d")
###me quedo con la humedad relativa y la temperatura
Temp_gamir_Feb21_May22 <- rbind(Temp_gamir_Feb21_Jun21,Temp_gamir_Jun21_May22)  
Temp_gamir_Feb21_May22 <- Temp_gamir_Feb21_May22[names(Temp_gamir_Feb21_May22) %in% c("date" ,"Temperatura_(C)", "Humedad_relativa")]

####le hago la media de temperatura al df Temp_gamir_Feb21_Jun21
Temp_gamir_Nov20_Feb21$Tmean <- rowMeans(Temp_gamir_Nov20_Feb21[, c("Tmin","Tmax")] , na.rm = T)
Temp_gamir_Nov20_Feb21$date <- as.Date(Temp_gamir_Nov20_Feb21$date)


clima$temp <- Temp_gamir_Feb21_May22
clima$temp_Feb21  <- Temp_gamir_Nov20_Feb21

#Humedad suelo
clima$Hum <- read_delim("Humedad_suelo_Modificado.csv", delim = ";" )


rm(Temp_gamir_Nov20_Feb21, Temp_gamir_Feb21_Jun21, Temp_gamir_Jun21_May22, Temp_gamir_Feb21_May22 )

###EW/LW/TRW/Area
Minicore_fielddata <- list()
Minicore_fielddata$Minicore_TRW <- read_excel_allsheets("Datos_Modificados_Qca.xlsx")
Minicore_fielddata$Datos_pie <- read_ods("Datos_Pie.ods")
Minicore_fielddata$Datos_pie <- split(Minicore_fielddata$Datos_pie, Minicore_fielddata$Datos_pie$Especie)
Minicore_fielddata$Datos_pie <- Minicore_fielddata$Datos_pie$QUCA

# setwd("C:/Minicores/Qca_Bruto/ImageJ/Tablas/a4-02-2021")
# name_documents <- list.files(pattern = '*.csv') ##hace una lista con todos los nombres de archivos csv de la carpeta
# Qca2020_21 <- list()
# Qca2020_21$Qca20 <- lapply(name_documents, read_delim, delim = ',') #se abren los documentos seleccionados
# names(Qca2020_21$Qca20) <- name_documents #conecta los nombre de la lista con los nombres de los documentos
# setwd("C:/Minicores/Qca_Bruto/ImageJ/Tablas/l19-1-2022")
# name_documents <- list.files(pattern = '*.csv') ##hace una lista con todos los nombres de archivos csv de la carpeta
# Qca2020_21$Qca21 <- lapply(name_documents, read_delim, delim = ',') #se abren los documentos seleccionados
# names(Qca2020_21$Qca21) <- name_documents #conecta los nombre de la lista con los nombres de los documentos
# rm(name_documents)

Qca2020_21 <- readRDS("Qca2020_21.rds")

###patogenos
Minicore_fielddata$phytophthora <- read_xlsx("Patogenos_y_textura.xlsx", sheet = "Gamir")


```

```{r clima, include=FALSE}
###creo una lista para meter los gráficos
clima_plot <- list()

#######Temperatura y VPD

temperatura <- clima$temp 

##calculo el SPD y el AVP
temperatura$SVP <- 0.6108 * exp((17.27 * temperatura$`Temperatura_(C)`) / (temperatura$`Temperatura_(C)` + 237.3))
temperatura$AVP <-  temperatura$SVP * (temperatura$Humedad_relativa / 100)
temperatura$VPD <-  temperatura$SVP - temperatura$AVP

##hago la media diaria de los valores de temperatura, humedad, maximo y minimo de temperatura diaria
temperatura <- split(temperatura, temperatura$date)
temperatura <- lapply(temperatura, function(x){
  df <-  data.frame("Tmean" = mean(x$`Temperatura_(C)`), "Tmin" = min(x$`Temperatura_(C)`), "Tmax" = max(x$`Temperatura_(C)`), "VPD" = mean(x$VPD) )
})
x <- 0
while(x < length(temperatura)){
  x <- x +1
  temperatura[[x]]$date <- names(temperatura[x])
}
rm(x)
temperatura <- do.call(rbind, Map(data.frame,temperatura ) )

temperatura$date <- as.Date(temperatura$date)

clima$VPD <- data.frame("date" = temperatura$date, "VPD" = temperatura$VPD)
temperatura$VPD <- NULL 

##ahora uno ambas temperaturas

clima$temp <- rbind(clima$temp_Feb21 ,temperatura)
clima$temp_Feb21 <- NULL

###sectorizo  las fechas tanto de prp como de temperatura


clima <- lapply(clima, function(x){
  ifelse("date" %in% names(x), x <-  x[x$date >= as.Date("2020-11-01") & x$date <= as.Date("2022-02-28"),], x <- x )  
              return(x)})

clima$prp$date <- as.Date(clima$prp$date)
precipitacion <- clima$prp
precipitacion <- precipitacion[names(precipitacion) %in% c("date","Prcp")]

precipitacion$year_month <- format(precipitacion$date, "%Y-%m")

group_month <- aggregate(Prcp ~ year_month, data = precipitacion, sum)
group_month$date <- as.Date(paste(group_month$year_month,'-01',sep = "")) 


###total de precipitacion
sum(precipitacion$Prcp)


##grafico precipitacion
precipitacion$doy <- yday(precipitacion$date)

clima_plot$prp <- ggplot()+
  geom_bar(data=precipitacion, aes(date, as.numeric(Prcp)),stat = "identity",
           show.legend = FALSE,position = "dodge", fill= "#00BFFF")+
  theme(panel.background = element_rect(fill = "white"),
          axis.line.x = element_line(colour="black"),
          axis.line.y = element_line(colour="black"))+
  scale_x_date(date_breaks = "1 month" ,date_labels = " ")+
  ylab("precipitation (mm)")+
  xlab(" ")





###figura 2

temperatura <- clima$temp

clima_plot$temp <-  ggplot() + geom_line(data=temperatura, aes(as.Date(date, "%y/%m/%d"), Tmean), color = "black", lwd= 0.9)+
geom_line(data=temperatura, aes(as.Date(date, "%y/%m/%d"), Tmax), color = "#FF3030", lwd= 0.9)+
  geom_line(data=temperatura, aes(as.Date(date, "%y/%m/%d"), Tmin), color = "#1C86EE", lwd= 0.9)+
  scale_y_continuous(name="Temperature (ºC)",breaks= c(-5,0,5,10,15,20,25,30,35,40),
                     expand = c(0,0))+
  scale_x_date(date_breaks = "1 month" ,date_labels = " ")+
  theme(panel.background = element_rect(fill = "white"),
          axis.line.x = element_line(colour="black"),
          axis.line.y = element_line(colour="black"))+
  xlab(" ")


####Humedad suelo

Hum_suelo <- clima$Hum

Hum_suelo <- split(Hum_suelo, Hum_suelo$Site)
Hum_suelo <- Hum_suelo$Gamir
nombre_columnas_fecha <- names(Hum_suelo)  ##cojo los nombres de la humedad de suelo (las fechas)
nombre_columnas_fecha <- nombre_columnas_fecha[!(nombre_columnas_fecha %in% c("Site", "Plot","Point","Treatment","Depth")) ]#elimino las variables que no contemplo para este plot

Hum_suelo <- reshape2::melt(Hum_suelo, id.vars=c("Site", "Plot","Point","Treatment","Depth"), 
                     measure.vars= nombre_columnas_fecha, 
                     value.name="values", 
                     variable.name="date")

##veo como se comportan las variables

Hum_suelo$site_tr <- paste0(Hum_suelo$Site, "_", Hum_suelo$Treatment)
ggplot(data= Hum_suelo, aes(x= as.Date(date, format = "%d/%m/%Y"), y= as.numeric(values), color= site_tr))+
  geom_point()+
  facet_grid(. ~ Depth)+
  geom_smooth()+
  scale_y_continuous(limits = c(0,60))


Hum_suelo$date <- as.Date(Hum_suelo$date, format = "%d/%m/%Y")
Hum_suelo$date1 <- as.numeric(Hum_suelo$date)
Hum_suelo$values <- as.numeric(Hum_suelo$values)
Hum_suelo$Depth <- as.factor(Hum_suelo$Depth)
Hum_suelo$Plot <- as.factor(Hum_suelo$Plot)
Hum_suelo$Treatment <- as.factor(Hum_suelo$Treatment)
Hum_suelo$Depth_point <- paste0(Hum_suelo$Point, "_", Hum_suelo$Depth)


Hum_suelo[duplicated(Hum_suelo[, c("Plot", "Point", "date1")]), ]

modelo_humedad <- gamm4(values ~ Treatment * Depth + s(date1, k = 10),
     random = ~(1|Plot/Point),
     data = Hum_suelo)

###duda si es el random Point o el Point_depth


summary(modelo_humedad$gam)


residuos <- residuals(modelo_humedad$mer)
qqnorm(residuos)
qqline(residuos)
hist(residuos) ###son normales
plot(modelo_humedad$mer)

###le hago el predict al modelo
predict_Humedad <- get_predictions(modelo_humedad$gam, 
                       cond = list( Depth = rep( unique(Hum_suelo$Depth), length(unique(Hum_suelo$date1))),
                                    date1= rep(unique(Hum_suelo$date1), each=8),
                                    Treatment= rep(unique(Hum_suelo$Treatment), each=4),
                                    Plot = 1,
                                    Point = 1, se= T))


predict_Humedad <- unique(predict_Humedad)

clima_plot$Hum <-  ggplot()+
  geom_point(data = Hum_suelo, aes(x= as.Date(Hum_suelo$date1), y= as.numeric(values), colour= Treatment), alpha= 0.1)+
  geom_line(data= predict_Humedad, aes(x= as.Date(date1), y= fit, colour = Treatment), lwd=0.9, show.legend = F)+
  facet_grid(. ~ Depth)+
  theme(panel.background = element_rect(fill = "white"),
          axis.line.x = element_line(colour="black"),
          axis.line.y = element_line(colour="black"))+
  scale_color_manual(values=c("#0000FF",'#CD3333'))+
  geom_ribbon(data= predict_Humedad, alpha=.3, mapping = aes(x=as.Date(date1), ymin= fit-CI, ymax= fit +CI, fill=Treatment),colour= NA, show.legend = F)+
  scale_fill_manual(values=c("#00EEEE",'#FF4040'))


###SPEI
 

clima$temp$PET <- hargreaves(Tmin=clima$temp$Tmin, Tmax=clima$temp$Tmax, lat= 36.569 )

clima$temp$prp <- clima$prp$Prcp

Prp_PET <- clima$temp$prp - clima$temp$PET

clima$SPEI <- spei(Prp_PET, scale =1 )

clima$SPEI <- data.frame(
  time = seq.Date(from = as.Date("2020-11-01"), by = "day", length.out = length(clima$SPEI$fitted)),
  spei = clima$SPEI$fitted
)


clima$SPEI$sing <- ifelse(as.numeric(clima$SPEI$spei) >= 0, "pos", "neg") 

clima_plot$SPEI <-  ggplot(clima$SPEI, aes(x = time, y = spei, col = sing, fill = sing)) +
  geom_bar(show.legend = F, stat = "identity") +
  scale_color_manual(values = c("pos" = "darkblue", "neg" = "red")) +
  scale_fill_manual(values = c("pos"  = "darkblue", "neg" = "red")) +
  labs( x= " ", y = "SPEI") +
  theme(panel.background = element_rect(fill = "white"),
          axis.line.x = element_line(colour="black"),
          axis.line.y = element_line(colour="black"))+
  scale_x_date(date_breaks = "1 month" ,date_labels = "%m")

##VPD

clima_plot$prp <- ggplot()+
  geom_line(data = clima$VPD, aes(x=date, y=VPD*10), color= "black", lwd=0.7, linetype= 8)+
  geom_bar(data=clima$prp, aes(date, as.numeric(Prcp)),stat = "identity",
           show.legend = FALSE,position = "dodge", fill= "#00BFFF")+
  theme(panel.background = element_rect(fill = "white"),
          axis.line.x = element_line(colour="black"),
          axis.line.y.left = element_line(colour="black"),
        axis.line.y.right = element_line(colour="black" ))+
  scale_x_date(date_breaks = "1 month" ,date_labels = " ")+
  scale_y_continuous(sec.axis = sec_axis(~(./10),name="VPD (Kpa)",breaks= c(1,2,3,4)),
                     name = "precipitation (mm)",breaks = c(0,10,20,30,40), expand = c(0,0))+
  xlab(" ") 

##Plots


plot_grid(clima_plot$temp,clima_plot$prp,clima_plot$SPEI, ncol = 1)


```

```{r Phenology canariensis_EW, include=FALSE}
Qca_phenology <- Minicore_fielddata$Minicore_TRW
Qca_phenology <- Qca_phenology[ names(Qca_phenology) != "ray_area"]


 ###elimino las columnas y las fechas que no son interesantes para este analisis
Qca_phenology <- lapply(Qca_phenology, function(x){
  if( !(("Inicio_EW" %in% names(x)) | ("Inicio_LW" %in% names(x)))) {return(NULL)}
  return(x)
})
Qca_phenology <- Qca_phenology[!sapply(Qca_phenology, is.null)]

Qca_phenology <- lapply(Qca_phenology, function(x) x[(names(x) %in% c("Plot", "Tratam", "indv","Inicio_EW", "Inicio_LW"))])

##añadimos una columna con las fechas del muestreo 
fechas <- c("02/02/2021", "18/03/2021","01/04/2021","15/04/2021","29/04/2021","13/05/2021","27/05/2021" ,"10/06/2021","22/07/2021","10/08/2021")
Qca_phenology <- mapply(cbind, Qca_phenology, "date"=as.Date(fechas, "%d/%m/%Y" ), SIMPLIFY=F)


####junto datos de pie a individuo
Minicore_fielddata$Datos_pie <- Minicore_fielddata$Datos_pie[!names(Minicore_fielddata$Datos_pie) %in% c("Especie", "Finca","Tratam","Plot")]
names(Minicore_fielddata$Datos_pie)[names(Minicore_fielddata$Datos_pie) == 'Árbol'] <- 'indv'

Qca_phenology <- lapply(Qca_phenology, function(x) {x <- merge(x,Minicore_fielddata$Datos_pie, by=c("indv"))
 if(!( "Inicio_LW" %in% names(x))){x$Inicio_LW <- NA}
 if(!("Inicio_EW" %in% names(x))){x$Inicio_EW <- NA}
return(x)
})

Qca_phenology <- do.call(rbind, Map(data.frame, Qca_phenology))

####empezamos a hacer el analisis de EW y LW

Qca_phenology$Inicio_EW <- as.factor(tolower(Qca_phenology$Inicio_EW))
Qca_phenology$Inicio_LW <- as.factor(tolower(Qca_phenology$Inicio_LW))
Qca_phenology$date_1 <- yday(Qca_phenology$date) ##se reformula la fecha en DOY
Qca_phenology$Tratam <- as.factor(Qca_phenology$Tratam)
Qca_phenology$Plot <- as.factor(Qca_phenology$Plot)
Qca_phenology$indv <- as.factor(Qca_phenology$indv)
Qca_phenology$Inicio_EW_bin <- ifelse(Qca_phenology$Inicio_EW == "si", 1, 0)
Qca_phenology$Inicio_LW_bin <- ifelse(Qca_phenology$Inicio_LW == "si", 1, 0)
####veo si hay colinealidad en mis variables
df <- data.frame("DBH"= Qca_phenology$DBH_.cm. , "H"= Qca_phenology$H_.cm. , "Dcopa"= Qca_phenology$Diametro_copa_.cm. )
cor(df)
summary(lm(formula = DBH ~ ., data = df)) #####correlacionado el H con el DBH, por lo tanto elijo la altura como variables
rm(df)
####mirar correlacion temporal correlation = corAR1(form = ~ as.numeric(date1) | Plot) esta forma

##modelos ########mirar con ELI pongo solo Plot ya que PLOT recoge casi toda la variabilidad
Qca_phenology_EW <- split(Qca_phenology, Qca_phenology$Inicio_EW_bin)
Qca_phenology_EW <- rbind(Qca_phenology_EW$`0`, Qca_phenology_EW$`1`)############Elimino los NA de esta columna


##########me sigue generando errores. Solo me converge con indv como random, deberiamos de revisarlo juntos.  Por ahora pongo solo indv como random


modelo1 <- glmer(data = Qca_phenology_EW, Inicio_EW_bin ~ scale(date_1) + scale(H_.cm.) + scale(Diametro_copa_.cm.) + Tratam + (1|indv) ,  family = binomial) ##29.0
summary(modelo1)$varcor
modelo2 <- glmer(data = Qca_phenology_EW, Inicio_EW_bin ~ scale(date_1) + scale(Diametro_copa_.cm.)+ Tratam  + (1|indv), family = binomial) ##36.9
modelo3 <- glmer(data = Qca_phenology_EW, Inicio_EW_bin ~ scale(date_1) + scale(H_.cm.)+ Tratam  + (1|indv), family = binomial)
modelo4 <- glmer(data = Qca_phenology_EW, Inicio_EW_bin ~ scale(date_1) + scale(H_.cm.)*scale(Diametro_copa_.cm.)+ Tratam  + + (1|indv), family = binomial) ##35.4 
modelo5 <- glmer(data = Qca_phenology_EW, Inicio_EW_bin ~ scale(date_1)+ Tratam  + (1|indv), family = binomial) #30.2

#########no me converge el modelo 1 y el 4, por lo cual no los utilizaré

model.sel(modelo1, modelo2, modelo3, modelo5) ###mejor modelo es el modelo 1


r2(modelo5)
summary(modelo5)
residuos <- residuals(modelo5)
qqnorm(residuos)
qqline(residuos)
hist(residuos) ###son normales

#####graficarlo

df <- expand.grid(
  Tratam = levels(Qca_phenology$Tratam),
  H_.cm. = mean(Qca_phenology$H_.cm., na.rm=TRUE),
  Diametro_copa_.cm. = mean(Qca_phenology$Diametro_copa_.cm., na.rm=TRUE),
  date_1 = seq(min(Qca_phenology$date_1), max(Qca_phenology$date_1), length.out = 100),
  indv= 5,
  Plot = 1
)


predict_Ci <- predictInterval(modelo5,
                              newdata = df,
                              level = 0.95,
                              type = "probability",
                              stat = "mean")

df$fit <- predict_Ci$fit
df$upr <- predict_Ci$upr
df$lwr <- predict_Ci$lwr
ggplot(data = df, aes(x = date_1, y=fit, colour = Tratam ))+
  geom_line()+
  geom_ribbon(aes(ymin = lwr, ymax = upr, fill = Tratam), alpha = 0.2, color = NA)+
  scale_color_manual(values= c("blue", "red"))+
  scale_fill_manual(values= c("blue", "red"))+
  scale_x_continuous(limits = c(30,150), breaks = seq(from=40, to=160, by=20))


# Día donde prob supera 0.5 = inicio estimado de EW
# inicio_est <- newdat$date_1[which.min(abs(newdat$prob_EW - 0.5))]
# inicio_est


```

```{r Phenology canariensis_LW, include=FALSE}
rm(modelo1, modelo2, modelo3, modelo4, modelo5, Qca_phenology_EW)
##modelos
Qca_phenology_LW <- split(Qca_phenology, Qca_phenology$Inicio_LW_bin )
Qca_phenology_LW <- rbind(Qca_phenology_LW$`0`, Qca_phenology_LW$`1`)############Elimino los NA de esta columna

##pasa lo mismo que en el apartado anterior pero con la particularidad de que ahora el r2 de los modelos genera issingular y que Conditional R2: 1.000 lo cual es imposible

modelo1 <- glmer(data = Qca_phenology_LW, Inicio_LW_bin ~ scale(date_1) + scale(H_.cm.) + scale(Diametro_copa_.cm.) + Tratam  + (1|indv), family = binomial) ##56.3
summary(modelo1)$varcor
modelo2 <- glmer(data = Qca_phenology_LW, Inicio_LW_bin ~ scale(date_1) + scale(Diametro_copa_.cm.)+ Tratam  + (1|indv), family = binomial) ##54.3
modelo3 <- glmer(data = Qca_phenology_LW, Inicio_LW_bin ~ scale(date_1) + scale(H_.cm.)+ Tratam  + (1|indv), family = binomial) ##53.9
modelo4 <- glmer(data = Qca_phenology_LW, Inicio_LW_bin ~ scale(date_1) + scale(H_.cm.)*scale(Diametro_copa_.cm.)+ Tratam  + (1|indv), family = binomial) ##58.7
modelo5 <- glmer(data = Qca_phenology_LW, Inicio_LW_bin ~ scale(date_1)+ Tratam  + (1|indv), family = binomial) #52.7

model.sel(modelo1, modelo3, modelo4, modelo5) ###mejor modelo es el modelo 5


r2(modelo5) ##########esto no es normal que me salga issingular en el r2
summary(modelo5)
residuos <- residuals(modelo5)
qqnorm(residuos)
qqline(residuos)
hist(residuos) ###son normales

#####graficarlo

df$indv <- 2
predict_Ci <- predictInterval(modelo5,
                              newdata = df,
                              level = 0.95,
                              type = "probability",
                              stat = "mean")

df$fit <- predict_Ci$fit
df$upr <- predict_Ci$upr
df$lwr <- predict_Ci$lwr
ggplot(data = df, aes(x = date_1, y=fit, colour = Tratam ))+
  geom_line()+
  geom_ribbon(aes(ymin = lwr, ymax = upr, fill = Tratam), alpha = 0.2, color = NA)+
  scale_color_manual(values= c("blue", "red"))+
  scale_fill_manual(values= c("blue", "red"))


rm(modelo1,modelo2, modelo3, modelo4, modelo5, Qca_phenology_LW)
```

```{r Análisis de 2020/2021 Qca, include=FALSE}
## EW

###datos
EW <- list("Qc2.20" = Qca2020_21$Qca20$a2QcC4F21.csv[c(1,20), ],"Qc3.20" = Qca2020_21$Qca20$b3QcC_4F21.csv[c(32,44, 48,49), ], "Qc5.20" =Qca2020_21$Qca20$c5QcC4F21.csv[c(10,21,23,32,43,57,64), ], "Qc8.20" = Qca2020_21$Qca20$d8QcC4F21.csv[c(1,3,9,18), ],"Qc9.20" = Qca2020_21$Qca20$e9QcC4F21.csv[c(19), ],"Qc10.20" = Qca2020_21$Qca20$f10QcC4F21.csv[c(7,18), ],"Qc18.20" = Qca2020_21$Qca20$g18QcS4F21.csv[c(8), ],"Qc19.20" = Qca2020_21$Qca20$h19QcS4F21.csv[c(1,3), ],"Qc26.20" = Qca2020_21$Qca20$i26QcS4F21.csv[c(1,19,30,31), ],"Qc30.20" = Qca2020_21$Qca20$j30QcCSF21.csv[c(14,30,42, 51,57), ], "Qc40.20" = Qca2020_21$Qca20$k40QcC4F21.csv[c(1,8,27), ], "Qc44.20" = Qca2020_21$Qca20$l44QcC4F21.csv[c(7,12,20,26,29), ],"Qc47.20" = Qca2020_21$Qca20$m47QcS4F21.csv[c(1,2,12,13,42,43), ],"Qc52.20" = Qca2020_21$Qca20$n52QcS4F21.csv[c(4,6,25,27,31,33,37,38,44), ]) #####se hace una lista con todos los vasos de EW del año 2020

EW_21 <- list("Qc2.21" = Qca2020_21$Qca21$a2QcC19E22.csv[c(1,9,11,12,14,16,17,24,28,29,31,35,38,43,45), ],"Qc3.21" = Qca2020_21$Qca21$b3QcC19E22.csv[c(1,29,30,35,55,58,59), ], "Qc5.21" =Qca2020_21$Qca21$c5QcC19E22.csv[c(1,6,13,15,19,24,32,37,39,40), ], "Qc9.21" = Qca2020_21$Qca21$d9QcC19E22.csv[c(18,27), ],"Qc18.21" = Qca2020_21$Qca21$h18QcS19E22.csv[c(19,21,23,32,36), ],"Qc19.21" = Qca2020_21$Qca21$i19QcS19E22.csv[c(1,23,36), ],"Qc30.21" = Qca2020_21$Qca21$j30QcS19E22.csv[c(2,9,16,21,25), ], "Qc36.21" = Qca2020_21$Qca21$k36QcC19E22.csv[c(1,6), ], "Qc40.21" = Qca2020_21$Qca21$m40QcC19E22.csv[c(1,16,29), ], "Qc44.21" = Qca2020_21$Qca21$n44QcC19E22.csv[c(5,10,19,42), ],"Qc47.21" = Qca2020_21$Qca21$o47QcS19E22.csv[c(1,3,4), ],"Qc52.21" = Qca2020_21$Qca21$r52QcS19E22.csv[c(7,13,21,29), ]) #####se hace una lista con todos los vasos de EW del año 2021

LW <- list("Qc2.20" = Qca2020_21$Qca20$a2QcC4F21.csv[-c(1,2,3,5,7,20,8,13,19,10,25,30,36,39), ],"Qc3.20" = Qca2020_21$Qca20$b3QcC_4F21.csv[-c(32,44, 48,49,20,42,34,14,41,43,35), ], "Qc5.20" =Qca2020_21$Qca20$c5QcC4F21.csv[-c(10,21,23,32,43,57,64,57,62,60,38,50,53,20,25,35,54,63,58,52), ], "Qc8.20" = Qca2020_21$Qca20$d8QcC4F21.csv[-c(1,3,9,18), ],"Qc9.20" = Qca2020_21$Qca20$e9QcC4F21.csv[-c(4,7,19,33,38,48,51,55,54,56,20,14,8,10,12,16,25,20), ],"Qc10.20" = Qca2020_21$Qca20$f10QcC4F21.csv[-c(7,18), ],"Qc18.20" = Qca2020_21$Qca20$g18QcS4F21.csv[-c(8), ],"Qc19.20" = Qca2020_21$Qca20$h19QcS4F21.csv[-c(1,3), ],"Qc26.20" = Qca2020_21$Qca20$i26QcS4F21.csv[-c(1,19,30,31), ],"Qc30.20" = Qca2020_21$Qca20$j30QcCSF21.csv[-c(14,30,42, 51,57,20,34,40,52,49,53,56,58,41,38), ], "Qc40.20" = Qca2020_21$Qca20$k40QcC4F21.csv[-c(1,8,27), ], "Qc44.20" = Qca2020_21$Qca20$l44QcC4F21.csv[-c(7,12,20,26,29), ],"Qc47.20" = Qca2020_21$Qca20$m47QcS4F21.csv[-c(1,2,12,13,42,43), ],"Qc52.20" = Qca2020_21$Qca20$n52QcS4F21.csv[-c(4,6,25,27,31,33,37,38,44), ]) #####se hace una lista con todos los vasos menos los de EW del año 2020

LW_21 <- list("Qc2.21" = Qca2020_21$Qca21$a2QcC19E22.csv[-c(1,9,11,12,14,16,17,24,28,29,31,35,38,43,45), ],"Qc3.21" = Qca2020_21$Qca21$b3QcC19E22.csv[-c(1,18,19,23,29,30,35,40,46,49,51,53,55,58,59,20,24,2,5,28,42,32), ], "Qc5.21" =Qca2020_21$Qca21$c5QcC19E22.csv[-c(1,6,13,15,19,24,32,37,39,40), ], "Qc9.21" = Qca2020_21$Qca21$d9QcC19E22.csv[-c(18,27), ],"Qc10.21" = Qca2020_21$Qca21$e10QcC19E22.csv[-c(12,22,26,27,33), ],"Qc18.21" = Qca2020_21$Qca21$h18QcS19E22.csv[-c(19,21,23,32,36), ],"Qc19.21" = Qca2020_21$Qca21$i19QcS19E22.csv[-c(1,23,36), ],"Qc30.21" = Qca2020_21$Qca21$j30QcS19E22.csv[-c(2,9,16,21,25), ], "Qc36.21" = Qca2020_21$Qca21$k36QcC19E22.csv[-c(1,6), ], "Qc40.21" = Qca2020_21$Qca21$m40QcC19E22.csv[-c(1,16,29), ], "Qc44.21" = Qca2020_21$Qca21$n44QcC19E22.csv[-c(5,8,10,19,33,38,42,21,13,26,40,46), ],"Qc47.21" = Qca2020_21$Qca21$o47QcS19E22.csv[-c(1,3,4), ],"Qc52.21" = Qca2020_21$Qca21$r52QcS19E22.csv[-c(7,13,21,29), ]) #####se hace una lista con todos los vasos de EW del año 2021, ademas elimino los fallos que tiene en la lectura de algunos vasos de la LW

LW <- c(LW, LW_21)
EW <- c(EW, EW_21)
LW_EW <- list()
LW_EW$EW <- EW
LW_EW$LW <- LW
rm(EW_21, LW_21, LW, EW)
###le hago una columna con su indv y year

n <- 0
while (n < length(LW_EW)) {
  n <- n +1
  x <- 0
  while(x < length(LW_EW[[n]])){
  x <- x +1
  LW_EW[[n]][[x]]$indv <- names(LW_EW[[n]])[x]
  ifelse(unique(grepl("20", LW_EW[[n]][[x]]$indv)), LW_EW[[n]][[x]]$year <- 2020, LW_EW[[n]][[x]]$year <- 2021  )
  LW_EW[[n]][[x]]$N_vessels <- length( LW_EW[[n]][[x]]$Area)
} 
  
}

rm(x,n)

####escribo bien la columna de individuos y uno los dataframes de EW/LW
LW_EW <-lapply(LW_EW, function(x){
  x <- lapply(x, function(y){
    
    y$indv <- gsub( "Qc", "",
                   gsub( ".20", "",
                         gsub( ".21", "", as.character(y$indv))))
  y <- y[c("indv", 'Area', 'Feret', "year", "N_vessels")]
  return(y)
    })
   x <- do.call(rbind.data.frame, x)
   return(x)
  })

control <- c(2,3,5,8,9,10,36,40,44)

###clasifico por tratamiento y primera visualizacion
LW_EW <- lapply(LW_EW, function(x){
  x$indv <- as.numeric(x$indv)
###Separamos entre control y sequia

x$treatment <- ifelse(x$indv %in% control, "control", "drought" )
x$Area_Feret <- 0.785*(x$Feret^2)

print(ggplot(data =x, aes(x= treatment, y= Area_Feret))+
  geom_violin()+
  geom_point())
return(x)
})

#elimino los valores anomalos
LW_EW$LW$Area_Feret <- ifelse(LW_EW$LW$Area_Feret >= 10, NA, LW_EW$LW$Area_Feret)
##lo grafico
lapply(LW_EW, function(x){

print(ggplot(data =x, aes(x= treatment, y= Area_Feret))+
  geom_violin()+
  geom_point())

})

########genero la columna de plot
plot <- data.frame("indv"= Minicore_fielddata$phytophthora$Tree, "Plot" = Minicore_fielddata$phytophthora$Plot)
LW_EW <- lapply(LW_EW, function(x){ x <- merge(x, plot, by= c("indv"))
x$Plot <- as.factor(x$Plot)
return(x)
})

####modelos ###########siempre que añado Plot me genera isSingular


modelo_EW <- lmer(data = as.data.frame(LW_EW$EW) , log(Area_Feret) ~treatment +(1|indv)) ###le hago el logaritmo ya que los datos no son normales
summary(modelo_EW) ######no hay diferencia entre tratamientosummary(modelo_EW) ######no hay diferencia entre tratamientosummary(modelo_EW) ######no hay diferencia entre tratamiento
residuos <- residuals(modelo_EW)
qqnorm(residuos)
qqline(residuos)
#######preguntar a ELI si lo hago con LMER o no #######################

aggregate(Area_Feret~ treatment,LW_EW$EW, mean )
aggregate(Area_Feret~ treatment,LW_EW$EW, se )

modelo_LW <- lmer(data = as.data.frame(LW_EW$LW) , log(Area_Feret) ~treatment + (1|indv)) ###le hago el logaritmo ya que los datos no son normales
summary(modelo_LW) ######no hay diferencia entre tratamiento
residuos <- residuals(modelo_LW)
qqnorm(residuos)
qqline(residuos)

aggregate(Area_Feret~ treatment,LW_EW$LW, mean )
aggregate(Area_Feret~ treatment,LW_EW$LW, se )

###numero de EW vessel por indv en el area

#######tengo que juntar el area y dividirlo para saber la frecuencia de vasos de EW en el anillo

##data frame con el area del anillo
Minicore20_21 <- list("year20" = Minicore_fielddata$Minicore_TRW$`2Feb21`, "year21" = Minicore_fielddata$Minicore_TRW$`19Ene22`)
Minicore20_21 <- eliminar_filas_NA_lista(Minicore20_21, "N_vasos")
Minicore20_21$year20$year <- 2020
Minicore20_21$year21$year <- 2021
Minicore20_21 <- lapply(Minicore20_21, function(x){
  x$TRW_mean <- rowMeans(x[ ,names(x) %in% c("TRW (mm) arriba", "TRW (mm) centro", "TRW (mm) Abajo")], na.rm = T)
  x <- x[c("indv", 'year', 'Plot', "Area","TRW_mean")]
  return(x)
})
Minicore20_21 <- do.call(rbind.data.frame, Minicore20_21)


########uno los datos anteriores para saber la densidad de vasos

EW_LW_N_vessels <- lapply(LW_EW, function(x){
  x$indv_year <- paste(x$indv, "_", x$year)
x <-  x[!duplicated(x$indv_year), ]
x <- merge(x, Minicore20_21, by= c("year", "indv") )
x$area_TRW <- x$Area.y
x$vesseldensity <- x$N_vessels/x$area_TRW
print(ggplot(data =x, aes(x= as.factor(year), y= vesseldensity, fill= treatment))+
  geom_boxplot())
return(x)
})

  


modelo_EW <- lmer(data = as.data.frame(EW_LW_N_vessels$EW), log(vesseldensity) ~ treatment + (1|as.factor(EW_LW_N_vessels$EW$indv))) ###le hago el logaritmo ya que los datos no son normales

summary(modelo_EW) ######no hay diferencia entre tratamientosummary(mPlotodelo_EW) ######no haysummary(modelo_EW) ######no hay diferencia entre tratamientosummary(mPlotodelo_EW) ######no haysummary(modelo_EW) ######no hay diferencia entre tratamientosummary(mPlotodelo_EW) ######no hay diferencia entre tratamiento
residuos <- residuals(modelo_EW)
qqnorm(residuos)
qqline(residuos)

aggregate(vesseldensity~ treatment,EW_LW_N_vessels$EW, mean )
aggregate(vesseldensity~ treatment,EW_LW_N_vessels$EW, se )


###############¿hago de mas años?


modelo_LW<- lmer(data = as.data.frame(EW_LW_N_vessels$LW) , log(vesseldensity) ~ treatment + (1|as.factor(EW_LW_N_vessels$LW$indv))) ###le hago el logaritmo ya que los datos no son normales
summary(modelo_LW) ######no hay diferencia entre tratamiento
r2(modelo_LW)
########revisarrrrr con Eli

residuos <- residuals(modelo_LW)
qqnorm(residuos)
qqline(residuos)

aggregate(vesseldensity~ treatment,EW_LW_N_vessels$LW, mean )
aggregate(vesseldensity~ treatment,EW_LW_N_vessels$LW, se )



###TRW
Minicore20_21$treatment <- ifelse(Minicore20_21$indv %in% control, "control", "drought" )

ggplot(data = Minicore20_21, aes(x= treatment, y= TRW_mean ))+
  geom_boxplot()

summary(lmer(data = Minicore20_21, TRW_mean ~ treatment + year + (1|indv)))

aggregate(TRW_mean~ treatment + year,Minicore20_21, mean )
aggregate(TRW_mean~ treatment + year,Minicore20_21, se )


#DBH y H
Minicore_fielddata$Datos_pie$Tratam <- ifelse(Minicore_fielddata$Datos_pie$indv %in% control, "control", "drought")

DBH_model <-  lm(data = as.data.frame(Minicore_fielddata$Datos_pie), `DBH_(cm)` ~ Tratam)
summary(DBH_model) ##no hay diferencias

H_model <- lm(data = as.data.frame(Minicore_fielddata$Datos_pie),  `H_(cm)` ~ Tratam)
summary(H_model) ##no hay diferencias

aggregate(`DBH_(cm)`~ Tratam, as.data.frame(Minicore_fielddata$Datos_pie), mean )
aggregate(`DBH_(cm)` ~ Tratam,as.data.frame(Minicore_fielddata$Datos_pie), se )
aggregate(`H_(cm)`~ Tratam, as.data.frame(Minicore_fielddata$Datos_pie), mean )
aggregate(`H_(cm)` ~ Tratam,as.data.frame(Minicore_fielddata$Datos_pie), se )

###ray area
Ray_area <- as.data.frame(Minicore_fielddata$Minicore_TRW$ray_area)

Ray_area <- Ray_area[!(is.na(Ray_area$Codigo) |Ray_area$Codigo == " ") ,  ] ###elimino las filas que no me afectan para este calculo

Ray_area <- pivot_longer(data = Ray_area, cols = c("Ray_2020", "Ray_2021"), names_to = "year", values_to = "Ray_area")

ggplot()+ geom_boxplot(data = Ray_area, aes(x= Tratam, y= Ray_area))


ray_model <- lmer(data= Ray_area, Ray_area ~ Tratam + (1|Árbol)) #########esta bien el random?
summary(ray_model)
r2(ray_model)
########revisarrrrr con Eli

residuos <- residuals(ray_model)
qqnorm(residuos)
qqline(residuos)

aggregate(Ray_area~ Tratam, Ray_area, mean )
aggregate(Ray_area~ Tratam, Ray_area, se )


###EW vulnerability index

LW_EW_AQ <- lapply(LW_EW, function(x){
  x$Feret <- x$Feret*1000
  x$D5 <- x$Feret^5
  x$D4 <- x$Feret^4
  x$D4_metros <- x$D4/(10^24)
  x <- split(x, x$year) #########separo por año y por individuo
  x <- lapply(x, function(n){n <- split(n, n$indv)
  return(n)}) 

  x <- lapply(x, function(y){
    y <- lapply(y, function(z){
      z <- data.frame("indv" = unique(z$indv), "N_vessels" = unique(z$N_vessels), "totalvesselarea"= sum(z$Area_Feret), "sumD4"= sum(z$D4), "sumD5"= sum(z$D5), "sumD4_metros"= sum(z$D4_metros), "year"= unique(z$year), "treatment"= unique(z$treatment), "Dmin_microm" = min(z$Feret) )})
    return(y)
  })
  return(x)
}) ######calculo D4 y su suma en todos los casos que tengo de muestreo


LW_EW_AQ <- lapply(LW_EW_AQ, function(x){
  x <- lapply(x, function(y){
    y <- lapply(y, function(z){
      z <- merge(z, Minicore20_21, by= c("indv", "year", "treatment"))

      z <- data.frame("indv" = z$indv, "year" = z$year, "treatment"= z$treatment,"N_vessels"= z$N_vessels ,"totalvesselarea"= z$totalvesselarea, "meanvesselarea"= z$totalvesselarea/ z$N_vessels, "vesselfrequency"= z$N_vessels/ z$Area, "dh"= z$sumD5/z$sumD4, "Kh"= (((3.14*998.2071)/(128*0.001002))*z$sumD4_metros), "Totalringarea"= z$Area, "vulindex" = z$Dmin/z$N_vessels)
      z$Ks <- z$Kh/z$Totalringarea
      
      return(z)
    })
    return(y)
  })
  return(x)
}) ######calculo del dh, kh, ks, vessel frequency y meanvesselarea

LW_EW_AQ <- lapply(LW_EW_AQ, function(x){
  x <- lapply(x, function(y){y <- do.call(rbind.data.frame, y)
  return(y)} )
  x <- do.call(rbind.data.frame, x)
    
    return(x)
}) #####lo uno todo en un data frame

LW_EW_AQ$LW <- LW_EW_AQ$LW[complete.cases(LW_EW_AQ$LW), ]

ggplot()+ geom_boxplot(data= as.data.frame(LW_EW_AQ$EW) , aes(x=as.factor(treatment), y= vulindex))
ggplot()+ geom_boxplot(data= as.data.frame(LW_EW_AQ$LW) , aes(x=as.factor(treatment), y= vulindex))
ggplot()+ geom_boxplot(data= as.data.frame(LW_EW_AQ$EW) , aes(x=as.factor(treatment), y=  Ks))
ggplot()+ geom_boxplot(data= as.data.frame(LW_EW_AQ$LW) , aes(x=as.factor(treatment), y= Ks))
ggplot()+ geom_boxplot(data= as.data.frame(LW_EW_AQ$EW) , aes(x=as.factor(treatment), y=  Kh))
ggplot()+ geom_boxplot(data= as.data.frame(LW_EW_AQ$LW) , aes(x=as.factor(treatment), y= Kh))

vulindex_model_EW <- lm(data= as.data.frame(LW_EW_AQ$EW), log(vulindex) ~ treatment )
vulindex_model_LW <- lm(data= as.data.frame(LW_EW_AQ$LW), log(vulindex) ~ treatment )
Ks_model_EW <- lm(data= as.data.frame(LW_EW_AQ$EW), log(Ks) ~ treatment)
Ks_model_LW <- lm(data= as.data.frame(LW_EW_AQ$LW), log(Ks) ~ treatment )
Kh_model_EW <- lm(data= as.data.frame(LW_EW_AQ$EW), log(Kh) ~ treatment)
Kh_model_LW <- lm(data= as.data.frame(LW_EW_AQ$LW), log(Kh) ~ treatment)

summary(vulindex_model_EW)
summary(vulindex_model_LW)
summary(Ks_model_EW)
summary(Ks_model_LW)
summary(Kh_model_EW)
summary(Kh_model_LW)
residuos <- residuals(vulindex_model_EW)
qqnorm(residuos)
qqline(residuos)

#####patogenos
Minicore_fielddata$phytophthora <- split(Minicore_fielddata$phytophthora, Minicore_fielddata$phytophthora$Species)
Minicore_fielddata$phytophthora$Alcornoque <- NULL

Minicore_fielddata$phytophthora <- data.frame("indv" = Minicore_fielddata$phytophthora$Quejigo$Tree, "Pci"= Minicore_fielddata$phytophthora$Quejigo$Pci2020, "treatment"= Minicore_fielddata$phytophthora$Quejigo$Drought, "Plot" = Minicore_fielddata$phytophthora$Quejigo$Block )
ggplot(data = Minicore_fielddata$phytophthora, aes(x=treatment, y=Pci))+ geom_point()

modelo_phytophthora <-  lmer(data = Minicore_fielddata$phytophthora, Pci ~ treatment+ (1|Plot)) ############tambien isSingular ¿lo dejo solo como lm?
summary(modelo_phytophthora)

####usar la distribucion binomial negativa  usando glmmTMB para comparar?¿ es lo que suele usar lorena
aggregate(Pci ~ treatment, Minicore_fielddata$phytophthora, mean )
aggregate(Pci ~ treatment, Minicore_fielddata$phytophthora, se )

```

```{r Diferencias TRW, include=FALSE}
###cojo los datos de TRW individual de cada fecha con el medio de cada fecha
TRW_2021 <- Minicore_fielddata$Minicore_TRW

#####elimino las diferentes listas que no me van a hacer falta
TRW_2021$`2Feb21` <- NULL
TRW_2021$`10AGOS_FENO` <- NULL
TRW_2021$ray_area <- NULL
TRW_2021$`18Marz2021` <- NULL

TRW_2021 <- eliminar_filas_NA_lista(TRW_2021, "TRW (mm) centro")

TRW_2021 <- lapply(TRW_2021, function(x){
    x$TRW_mean <- rowMeans(x[ ,names(x) %in% c("TRW (mm) arriba", "TRW (mm) centro", "TRW (mm) Abajo")], na.rm = T)
  x <- data.frame("indv"= x$indv, 'Plot'= x$Plot,"TRW_mean"= x$TRW_mean, "TRW_2020"= x$`2020_TRW`)
  return(x)
})

fechas <- as.Date(c("01/04/21", "15/04/21", "29/04/21", "13/05/21", "27/05/21", "10/06/21", "22/07/21", "26/08/21", "09/09/21", "14/10/21", "18/11/21", "16/12/21", "19/01/22", "08/02/22"),format = "%d/%m/%y") 

#####le uno la fecha
x <- 0
while(x < length(TRW_2021)){
  x <- x+1
  TRW_2021[[x]]$date <- fechas[x]
  
}

TRW_2021 <- do.call(rbind, Map(data.frame, TRW_2021)) ####lo uno todo


# cargo los datos de patogenicidad

TRW_2021 <- merge(TRW_2021,Minicore_fielddata$phytophthora, by=c("indv", "indv"))
TRW_2021 <- merge(TRW_2021,Minicore_fielddata$Datos_pie, by=c("indv"))

TRW_2021 <- TRW_2021[!names(TRW_2021) %in% c("Plot.x", "Plot.y","Finca","Tratam","Especie","Árbol")]


ggplot(data = TRW_2021, aes(x=date, y=TRW_mean, colour = treatment))+ geom_point()+
  geom_smooth()


####ahora calculo el TRW diario entre fechas
TRW_2021 <- split(TRW_2021, TRW_2021$indv)
diference_0 <- c(0)
#esta en mm, lo paso a microm
TRW_2021 <- lapply(TRW_2021, function(x){
  x <-  x[order(x$date), ]
  
  ###diferencia entre fechas
  diference_0 <-  c(0) 
  diference_Date <- c(diference_0, diff.Date(x$date))
  x$diference_Date <- diference_Date
  
  ######hago la proporcion de TRW con 2020 ###version a partir de la media del año 2020 con el 80%
  # mean_TRW_indv <- mean(x$TRW_2020)
  # x$TRW_propTRW2021 <- (x$TRW_mean*mean_TRW_indv)/x$TRW_2020
  # x$TRW_propTRW2021_mod1 <- x$TRW_propTRW2021
  # 
  # z <- 1 ###empiezo en el 2 ya que fila 1 no se puede comparar con la 0
  # while(z < length(x$indv)){
  #   z <- z+1
  #   if( (x$TRW_propTRW2021_mod1[z]/x$TRW_propTRW2021_mod1[z-1]) < 0.85){x$TRW_propTRW2021_mod1[z] <- x$TRW_propTRW2021_mod1[z-1]}  }
  
  ###proporcion con el 2020 con respecto a su fecha
  x$TRW_propTRW2021 <- (x$TRW_mean)/x$TRW_2020

  
  
  return(x)
}) ###duda Eli MIRAR LOS ERRORES CON ELLA, MUCHAS MEDICIONES NEGATIVAS

TRW_2021 <- lapply(TRW_2021, function(x){
  z <- 1 ###empiezo en el 2 ya que fila 1 no se puede comparar con la 0
  while(z < length(x$indv)){
    z <- z+1
    x$TRW_propTRW2021_mod <- x$TRW_propTRW2021
    if( (x$TRW_propTRW2021_mod[z]/x$TRW_propTRW2021_mod[z-1]) < 0.8){x$TRW_propTRW2021_mod[z] <- x$TRW_propTRW2021_mod[z-1]}  }
  return(x)
}) #############la nueva columna "TRW_propTRW2021_mod" significa: si el valor de TRW en cierta fecha es menor que la anterior fecha a un 80%, me posiciona el valor anterior, así identifico mejor los valores anomalos

#####modifico los valores anomalos, donde si es mucho mayor pongo el valor de TRW la fecha siguiente
TRW_2021$`52`$TRW_propTRW2021_mod[7] <- TRW_2021$`52`$TRW_propTRW2021_mod[8]
TRW_2021$`36`$TRW_propTRW2021_mod[9] <- TRW_2021$`36`$TRW_propTRW2021_mod[10]
TRW_2021$`19`$TRW_propTRW2021_mod[9] <- TRW_2021$`19`$TRW_propTRW2021_mod[10] 
TRW_2021$`18`$TRW_propTRW2021_mod[10] <- TRW_2021$`19`$TRW_propTRW2021_mod[11]
TRW_2021$`10`$TRW_propTRW2021_mod[6] <- TRW_2021$`10`$TRW_propTRW2021_mod[7]
TRW_2021$`3`$TRW_propTRW2021_mod[10] <- TRW_2021$`3`$TRW_propTRW2021_mod[11]
TRW_2021$`8`$TRW_propTRW2021_mod[5] <- TRW_2021$`8`$TRW_propTRW2021_mod[6]
TRW_2021$`19`$TRW_propTRW2021_mod[13] <- TRW_2021$`19`$TRW_propTRW2021_mod[12]

TRW_2021 <- lapply(TRW_2021, function(x){
   
  x$diference_TRW <- c(diference_0, diff(x$TRW_propTRW2021_mod))
  x$TRWday_micras <- (x$diference_TRW/x$diference_Date)*1000 ###si sale negativo por mas de 5 micras que me lo devuelva para revisar
  x$TRWday_micras[1] <- 0
  x$TRWday_micras <- ifelse(x$TRWday_micras < 0, 0, x$TRWday_micras)
  
  return(x)
}) #####hago el incremento de TRW diario en micras (leer los comentarios interiores) AQUI SE VEN LO DE LOS NUMEROS NEGATIVOS 

 
TRW_2021 <- do.call(rbind, Map(data.frame, TRW_2021)) ####lo uno todo

TRW_2021$treatment <- ifelse(TRW_2021$indv %in% control, "control", "drought")


ggplot(TRW_2021, aes(x=date, y=TRWday_micras, colour = treatment))+
  geom_point()+
  geom_smooth()

########modelos de crecimiento


##########saber cuanto a crecido y en qué fechas para saber los vasos nuevos en cada fecha


```

```{r Todos los Cortes_Qca, include=FALSE}
####1-ABRIL-2021
D1Abr21 <-read_excel("C:/Minicores/R_analisis/Datos_Modificados_Qca.xlsx", 
    sheet = "1Abr2021") ###abro el archivo
D1Abr21 <- D1Abr21[!is.na(D1Abr21$Codigo),] ###elimino los individuos que no se han medido
D1Abr21 <- D1Abr21[!(D1Abr21$N_vasos <= 0),] ###elimino los individuos que se han medido pero no hay crecimiento anual


names <- D1Abr21$indv
path <-  "C:/Minicores/Qca_Bruto/ImageJ/Tablas/c1-4-2021"
setwd(path)
name_documents <- list.files(pattern = '*.csv')
c1A21 <- lapply(name_documents, read_delim, delim = ',')

names(c1A21) <- names
c1A21 <- lapply(c1A21, function(x) Feret_converter_analisistemporal(x,"mm"))

c1A21 <- bind_rows(c1A21) 
rownames(c1A21) <- names 
c1A21$indv <- names
D1Abr21 <- mutate(D1Abr21, TRW_mean = rowMeans(select(D1Abr21, 
                                              c("TRW (mm) arriba","TRW (mm) centro","TRW (mm) Abajo")), na.rm = TRUE))
D1Abr21 <- select_columns(D1Abr21)
c1A21 <- merge(c1A21, D1Abr21, by= c("indv", "indv"))
c1A21 <- Vessel_measurement(c1A21)


####15-Abril-2021

D15A21 <-read_excel("C:/Minicores/R_analisis/Datos_Modificados_Qca.xlsx", 
    sheet = "15Abr2021")
D15A21 <- D15A21[!is.na(D15A21$Codigo),]
D15A21 <- D15A21[!(D15A21$N_vasos <= 0),]

names <- D15A21$indv
path <-  "C:/Minicores/Qca_Bruto/ImageJ/Tablas/d15-4-2021"
setwd(path)
name_documents <- list.files(pattern = '*.csv')
DD15A21 <- lapply(name_documents, read_delim, delim = ',')


names(DD15A21) <- names
DD15A21 <- lapply(DD15A21, function(x) Feret_converter_analisistemporal(x,"mm"))
DD15A21 <- bind_rows(DD15A21) 
rownames(DD15A21) <- names 
DD15A21$indv <- names
D15A21 <- mutate(D15A21, TRW_mean = rowMeans(select(D15A21, 
                                              c("TRW (mm) arriba","TRW (mm) centro","TRW (mm) Abajo")), na.rm = TRUE))
D15A21 <- select_columns(D15A21)
DD15A21 <- merge(DD15A21, D15A21, by= c("indv", "indv"))
DD15A21 <- Vessel_measurement(DD15A21)


##29-Abril-2021

D29Abr21 <-read_excel("C:/Minicores/R_analisis/Datos_Modificados_Qca.xlsx", 
    sheet = "29Abr21")
D29Abr21 <- D29Abr21[!is.na(D29Abr21$Codigo),]
D29Abr21 <- D29Abr21[!(D29Abr21$N_vasos <= 0),]



names <- D29Abr21$indv
path <-  "C:/Minicores/Qca_Bruto/ImageJ/Tablas/e29-4-2021"
setwd(path)
name_documents <- list.files(pattern = '*.csv')
e29Abr21<- lapply(name_documents, read_delim, delim = ',')
names(e29Abr21) <- names
e29Abr21 <- lapply(e29Abr21, function(x) Feret_converter_analisistemporal(x,"mm"))
e29Abr21 <- bind_rows(e29Abr21) 
rownames(e29Abr21) <- names 
e29Abr21$indv <- names
D29Abr21 <- mutate(D29Abr21, TRW_mean = rowMeans(select(D29Abr21, 
                                              c("TRW (mm) arriba","TRW (mm) centro","TRW (mm) Abajo")), na.rm = TRUE))
D29Abr21 <- select_columns(D29Abr21)
e29Abr21 <- merge(e29Abr21, D29Abr21, by= c("indv", "indv"))
e29Abr21 <- Vessel_measurement(e29Abr21)


##10-Junio-2021

D10J211 <-read_excel("C:/Minicores/R_analisis/Datos_Modificados_Qca.xlsx", 
    sheet = "10Jun2021")
D10J211 <- D10J211[!is.na(D10J211$Codigo),]
D10J211 <- D10J211[!(D10J211$N_vasos <= 0),]

names <- D10J211$indv
path <-  "C:/Minicores/Qca_Bruto/ImageJ/Tablas/f10-6-2021"
setwd(path)
name_documents <- list.files(pattern = '*.csv')
f10J211<- lapply(name_documents, read_delim, delim = ',')
names(f10J211) <- names
f10J211 <- lapply(f10J211, function(x) Feret_converter_analisistemporal(x,"mm"))
f10J211 <- bind_rows(f10J211) 
rownames(f10J211) <- names 
f10J211$indv <- names
D10J211 <- mutate(D10J211, TRW_mean = rowMeans(select(D10J211, 
                                              c("TRW (mm) arriba","TRW (mm) centro","TRW (mm) Abajo")), na.rm = TRUE))
D10J211 <- select_columns(D10J211)
f10J211 <- merge(f10J211, D10J211, by= c("indv", "indv"))
f10J211 <- Vessel_measurement(f10J211)


##22-Julio-2021

D22J21 <-read_excel("C:/Minicores/R_analisis/Datos_Modificados_Qca.xlsx", 
    sheet = "22Jul2021")
D22J21 <- D22J21[!is.na(D22J21$Codigo),]
D22J21 <- D22J21[!(D22J21$N_vasos <= 0),]

names <- D22J21$indv
path <-  "C:/Minicores/Qca_Bruto/ImageJ/Tablas/g22-7-2021"
setwd(path)
name_documents <- list.files(pattern = '*.csv')
g22J21<- lapply(name_documents, read_delim, delim = ',')
names(g22J21) <- names
g22J21 <- lapply(g22J21, function(x) Feret_converter_analisistemporal(x,"mm"))
g22J21 <- bind_rows(g22J21) 
rownames(g22J21) <- names 
g22J21$indv <- names
D22J21 <- mutate(D22J21, TRW_mean = rowMeans(select(D22J21, 
                                              c("TRW (mm) arriba","TRW (mm) centro","TRW (mm) Abajo")), na.rm = TRUE))
D22J21 <- select_columns(D22J21)
g22J21 <- merge(g22J21, D22J21, by= c("indv", "indv"))
g22J21 <- Vessel_measurement(g22J21)


##9-septiembre-2021

D9S21 <-read_excel("C:/Minicores/R_analisis/Datos_Modificados_Qca.xlsx", 
    sheet = "9Sep2021")
D9S21 <- D9S21[!is.na(D9S21$Codigo),]
D9S21 <- D9S21[!(D9S21$N_vasos <= 0),]

names <- D9S21$indv
path <-  "C:/Minicores/Qca_Bruto/ImageJ/Tablas/h9-9-2021"
setwd(path)
name_documents <- list.files(pattern = '*.csv')
h9S21<- lapply(name_documents, read_delim, delim = ',')
names(h9S21) <- names
h9S21 <- lapply(h9S21, function(x) Feret_converter_analisistemporal(x,"mm"))
h9S21 <- bind_rows(h9S21) 
rownames(h9S21) <- names 
h9S21$indv <- names
D9S21 <- mutate(D9S21, TRW_mean = rowMeans(select(D9S21, 
                                              c("TRW (mm) arriba","TRW (mm) centro","TRW (mm) Abajo")), na.rm = TRUE))
D9S21 <- select_columns(D9S21)
h9S21 <- merge(h9S21, D9S21, by= c("indv", "indv"))
h9S21 <- Vessel_measurement(h9S21)



##14-Octubre-2021

D14O21 <-read_excel("C:/Minicores/R_analisis/Datos_Modificados_Qca.xlsx", 
    sheet = "14Oct2021")
D14O21 <- D14O21[!is.na(D14O21$Codigo),]
D14O21 <- D14O21[!(D14O21$N_vasos <= 0),]

names <- D14O21$indv
path <-  "C:/Minicores/Qca_Bruto/ImageJ/Tablas/i14-10-2021"
setwd(path)
name_documents <- list.files(pattern = '*.csv')
i14O21<- lapply(name_documents, read_delim, delim = ',')
names(i14O21) <- names
i14O21 <- lapply(i14O21, function(x) Feret_converter_analisistemporal(x,"mm"))
i14O21 <- bind_rows(i14O21) 
rownames(i14O21) <- names 
i14O21$indv <- names
D14O21 <- mutate(D14O21, TRW_mean = rowMeans(select(D14O21, 
                                              c("TRW (mm) arriba","TRW (mm) centro","TRW (mm) Abajo")), na.rm = TRUE))
D14O21 <- select_columns(D14O21)
i14O21 <- merge(i14O21, D14O21, by= c("indv", "indv"))
i14O21 <- Vessel_measurement(i14O21)


##18-Noviembre-2021

D18Nov21 <-read_excel("C:/Minicores/R_analisis/Datos_Modificados_Qca.xlsx", 
    sheet = "18Nov2021")
D18Nov21 <- D18Nov21[!is.na(D18Nov21$Codigo),]
D18Nov21 <- D18Nov21[!(D18Nov21$N_vasos <= 0),]

names <- D18Nov21$indv
path <-  "C:/Minicores/Qca_Bruto/ImageJ/Tablas/j18-11-2021"
setwd(path)
name_documents <- list.files(pattern = '*.csv')
j18Nov21<- lapply(name_documents, read_delim, delim = ',')
names(j18Nov21) <- names
j18Nov21 <- lapply(j18Nov21, function(x) Feret_converter_analisistemporal(x,"mm"))
j18Nov21 <- bind_rows(j18Nov21) 
rownames(j18Nov21) <- names 
j18Nov21$indv <- names
D18Nov21 <- mutate(D18Nov21, TRW_mean = rowMeans(select(D18Nov21, 
                                              c("TRW (mm) arriba","TRW (mm) centro","TRW (mm) Abajo")), na.rm = TRUE))
D18Nov21 <- select_columns(D18Nov21)
j18Nov21 <- merge(j18Nov21, D18Nov21, by= c("indv", "indv"))
j18Nov21 <- Vessel_measurement(j18Nov21)


##16-Diciembre-2021
D16Dic21 <-read_excel("C:/Minicores/R_analisis/Datos_Modificados_Qca.xlsx", 
    sheet = "16Dic2021")
D16Dic21 <- D16Dic21[!is.na(D16Dic21$Codigo),]
D16Dic21 <- D16Dic21[!(D16Dic21$N_vasos <= 0),]

names <- D16Dic21$indv
path <-  "C:/Minicores/Qca_Bruto/ImageJ/Tablas/K16-12-2021"
setwd(path)
name_documents <- list.files(pattern = '*.csv')
k16Dic21<- lapply(name_documents, read_delim, delim = ',')
names(k16Dic21) <- names
k16Dic21 <- lapply(k16Dic21, function(x) Feret_converter_analisistemporal(x,"mm"))
k16Dic21 <- bind_rows(k16Dic21) 
rownames(k16Dic21) <- names 
k16Dic21$indv <- names
D16Dic21 <- mutate(D16Dic21, TRW_mean = rowMeans(select(D16Dic21, 
                                              c("TRW (mm) arriba","TRW (mm) centro","TRW (mm) Abajo")), na.rm = TRUE))
D16Dic21 <- select_columns(D16Dic21)
k16Dic21 <- merge(k16Dic21, D16Dic21, by= c("indv", "indv"))
k16Dic21 <- Vessel_measurement(k16Dic21)


##19-Enero-2022
D19En22 <-read_excel("C:/Minicores/R_analisis/Datos_Modificados_Qca.xlsx", 
    sheet = "19Ene22")
D19En22 <- D19En22[!is.na(D19En22$Codigo),]
D19En22 <- D19En22[!(D19En22$N_vasos <= 0),]

names <- D19En22$indv
path <-  "C:/Minicores/Qca_Bruto/ImageJ/Tablas/l19-1-2022"
setwd(path)
name_documents <- list.files(pattern = '*.csv')
l19En22<- lapply(name_documents, read_delim, delim = ',')
names(l19En22) <- names
l19En22 <- lapply(l19En22, function(x) Feret_converter_analisistemporal(x,"mm"))
l19En22 <- bind_rows(l19En22) 
rownames(l19En22) <- names 
l19En22$indv <- names
D19En22 <- mutate(D19En22, TRW_mean = rowMeans(select(D19En22, 
                                              c("TRW (mm) arriba","TRW (mm) centro","TRW (mm) Abajo")), na.rm = TRUE))
D19En22 <- select_columns(D19En22)
l19En22 <- merge(l19En22, D19En22, by= c("indv", "indv"))
l19En22 <- Vessel_measurement(l19En22)



##8-Febrero-2022

D8Feb22 <-read_excel("C:/Minicores/R_analisis/Datos_Modificados_Qca.xlsx", 
    sheet = "8Feb22")
D8Feb22 <- D8Feb22[!is.na(D8Feb22$Codigo),]
D8Feb22 <- D8Feb22[!(D8Feb22$N_vasos <= 0),]

names <- D8Feb22$indv
path <-  "C:/Minicores/Qca_Bruto/ImageJ/Tablas/m8-2-2022"
setwd(path)
name_documents <- list.files(pattern = '*.csv')
m8Feb22<- lapply(name_documents, read_delim, delim = ',')
names(m8Feb22) <- names
m8Feb22 <- lapply(m8Feb22, function(x) Feret_converter_analisistemporal(x,"mm"))
m8Feb22 <- bind_rows(m8Feb22) 
rownames(m8Feb22) <- names 
m8Feb22$indv <- names
D8Feb22 <- mutate(D8Feb22, TRW_mean = rowMeans(select(D8Feb22, 
                                              c("TRW (mm) arriba","TRW (mm) centro","TRW (mm) Abajo")), na.rm = TRUE))
D8Feb22 <- select_columns(D8Feb22)
m8Feb22 <- merge(m8Feb22, D8Feb22, by= c("indv", "indv"))
m8Feb22 <- Vessel_measurement(m8Feb22)


```

```{r Unificacion Cortes_Qca, include=FALSE}
Cortes_Qca <- list("c1A21" =c1A21,"DD15A21"=DD15A21,"e29Abr21" = e29Abr21, "f10J211" = f10J211, "g22J21"=g22J21,    "h9S21"=h9S21 ,"i14O21"=i14O21, 
               "j18Nov21" = j18Nov21, "k16Dic21"=k16Dic21, "l19En22" = l19En22 ,"m8Feb22" = m8Feb22)

fechas <- as.Date(c("2021/04/01", "2021/04/15", "2021/04/29", "2021/06/10", "2021/07/22" ,"2021/09/09","2021/10/14", "2021/11/18","2021/12/16", "2022/01/19", "2022/02/08"))

x <- 0
while (x < length(Cortes_Qca)) {
  x <- x +1
  Cortes_Qca[[x]]$date <- fechas[x]
}

Cortes_Qca <- do.call(rbind, Map(data.frame, Cortes_Qca))



Cortes_Qca$vessel_frequency[Cortes_Qca$vessel_frequency >= 100] <- 50
Cortes_Qca$Dh[Cortes_Qca$Dh >= 80] <- 0.09895


###hacer modelo de dh y de vessel frequency modelo gamm


Cortes_Qca$date1 <- as.numeric(Cortes_Qca$date)
Cortes_Qca$vessel_frequency
Cortes_Qca$Plot <- ifelse( (Cortes_Qca$indv == 2) | (Cortes_Qca$indv == 3) | (Cortes_Qca$indv == 5), 1,
                           ifelse((Cortes_Qca$indv == 8) | (Cortes_Qca$indv == 9) | (Cortes_Qca$indv == 10), 2 ,
                                  ifelse((Cortes_Qca$indv == 18) | (Cortes_Qca$indv == 19), 3 ,
                                         ifelse((Cortes_Qca$indv == 26) | (Cortes_Qca$indv == 30), 4 ,
                                  ifelse((Cortes_Qca$indv == 36) | (Cortes_Qca$indv == 40) | (Cortes_Qca$indv == 44), 5 ,
                                  ifelse((Cortes_Qca$indv == 47) | (Cortes_Qca$indv == 52), 6 , FALSE))))))

Cortes_Qca_modelo <- merge(Cortes_Qca, DBH_H, by= c("indv","indv"))
Cortes_Qca_modelo[63, 14 ] = 53
Cortes_Qca_modelo[16, 14 ] = 60

shapiro.test(Cortes_Qca_modelo$Dh)
Cortes_Qca_modelo$Plot <- as.factor(Cortes_Qca_modelo$Plot)
Cortes_Qca_modelo$indv <- as.factor(Cortes_Qca_modelo$indv)

# modelo_dh1 <- gamm4(Dh ~ s(date1)+ Tratam + s(DBH_.cm.),data = Cortes_Qca_modelo, random=~(1|Plot/indv))
# modelo_dh2 <- gamm4(Dh ~ s(date1)+ Tratam + s(Diametro_copa_.cm.),data = Cortes_Qca_modelo, random=~(1|Plot/indv))
# modelo_dh3 <- gamm4(Dh ~ s(date1)+ s(DBH_.cm.) + s(Diametro_copa_.cm.),data = Cortes_Qca_modelo, random=~(1|Plot/indv))
# 
# model.sel(modelo_dh1$mer, modelo_dh2$mer,modelo_dh3$mer)  ##da significativo  el modelo 1, siendo el mejor modelo, aunque no hay mucha diferencia con el modelo 2, siendo más simple el 2, por ello elijo el modelo 2
# summary(modelo_dh1$gam)
# 
# 
# # simulateResiduals(modelo_dh1$mer, plot = T)
# qqnorm(modelo_dh1$gam$residuals)
# qqline(modelo_dh1$gam$residuals)
# hist(modelo_dh1$gam$residuals) ###es el mejor modelo y sigue la normalidad
# 
# summary(modelo_dh1$gam)
# 
# #############no es significativa la tendencia de Dh
# pred2 <- get_predictions(modelo_dh1$gam, 
#                        cond = list(date1 = seq(min(Cortes_Qca_modelo$date1, na.rm=T),
#                                             max(Cortes_Qca_modelo$date1, na.rm=T), 
#                                             length.out = nrow(Cortes_Qca_modelo )),
#                                   Tratam = c("Control", "Sequía"),
#                                   se=T))
# 
# pred2$date <- as.Date(pred2$date1)
# 
# ggplot(data=pred2)+
#   geom_line(mapping = aes(x=date, y=fit, color= Tratam), show.legend = F)+
#   geom_ribbon(alpha=.4,mapping = aes(x=date, ymin=fit-CI, ymax=fit+CI, fill=Tratam), show.legend = T)+
#   geom_point(data = Cortes_Qca_modelo, mapping =  aes(x=date, y=as.numeric(Dh), color=Tratam), show.legend = F)+
#   scale_color_manual(values = c("#1E90FF","#FF4040"))+
#   scale_fill_manual(values = c("#97FFFF","#FF6A6A"))+
#   theme(panel.background = element_rect(fill = "white"),
#           axis.line.x = element_line(colour="black"),
#           axis.line.y = element_line(colour="black"),
#         axis.text = element_text(color = "black",size = 12),
#         axis.ticks.length  = unit(0.1, "cm"))+
#   scale_x_date(date_breaks = "2 month" ,date_labels = "%m")+
#   ylab("Dh")


#############################

######hora hago los cambios para la vessel frequency

shapiro.test(Cortes_Qca_modelo$vessel_frequency) ##no es normal, por lo cual lo transformo
qqnorm(Cortes_Qca_modelo$vessel_frequency)
qqline(Cortes_Qca_modelo$vessel_frequency)
hist(Cortes_Qca_modelo$vessel_frequency)
skewness(Cortes_Qca_modelo$vessel_frequency, na.rm = TRUE) #veo que dispersion tiene los datos

Cortes_Qca_modelo$vessel_frequency_trans <- log10(Cortes_Qca_modelo$vessel_frequency) ##realizo la transformacion
hist(Cortes_Qca_modelo$vessel_frequency_trans)

qqnorm(Cortes_Qca_modelo$vessel_frequency_trans)
qqline(Cortes_Qca_modelo$vessel_frequency_trans)
shapiro.test(Cortes_Qca_modelo$vessel_frequency_trans) ###veo que mis datos han mejorado la normalidad

 Cortes_Qca_modelo$vessel_frequency_trans <- ifelse( (Cortes_Qca_modelo$date1 == 18977 ) & (Cortes_Qca_modelo$Tratam == "Control" ) &  (Cortes_Qca_modelo$vessel_frequency_trans < 1 ), 1.5, Cortes_Qca_modelo$vessel_frequency_trans)
 
 Cortes_Qca_modelo$DBH_.cm. <-  Cortes_Qca_modelo$`DBH_(cm)`
  Cortes_Qca_modelo$Diametro_copa_.cm. <-  Cortes_Qca_modelo$`Diametro_copa_(cm)`
 

modelo1_vesselfreq <- gamm4(vessel_frequency_trans ~ s(date1)+ Tratam  + s(DBH_.cm.),data = Cortes_Qca_modelo , random=~(1|Plot/indv))
modelo2_vesselfreq <- gamm4(vessel_frequency_trans ~ s(date1)+ Tratam + s(Diametro_copa_.cm.) ,data = Cortes_Qca_modelo, random=~(1|Plot/indv))
modelo3_vesselfreq <- gamm4(vessel_frequency_trans ~ s(date1)  + s(DBH_.cm.) + s(Diametro_copa_.cm.),data = Cortes_Qca_modelo, random=~(1|Plot/indv))
modelo4_vesselfreq <- gamm4(vessel_frequency_trans ~ s(date1)  + s(DBH_.cm.),data = Cortes_Qca_modelo, random=~(1|Plot/indv))
modelo5_vesselfreq <- gamm4(vessel_frequency_trans ~ s(date1)  + s(Diametro_copa_.cm.),data = Cortes_Qca_modelo, random=~(1|Plot/indv))
modelo6_vesselfreq <- gamm4(vessel_frequency_trans ~ s(date1)  + Tratam,data = Cortes_Qca_modelo, random=~(1|Plot/indv))
modelo7_vesselfreq <- gamm4(vessel_frequency_trans ~ s(date1)+ Tratam  + s(DBH_.cm.) + s(Diametro_copa_.cm.),data = Cortes_Qca_modelo , random=~(1|Plot/indv))


model.sel(modelo1_vesselfreq$mer, modelo2_vesselfreq$mer,modelo3_vesselfreq$mer, modelo4_vesselfreq$mer, modelo5_vesselfreq$mer, modelo6_vesselfreq$mer, modelo7_vesselfreq$mer) ###el mas significativo seria el 2
summary(modelo6_vesselfreq$gam)
qqnorm(modelo1_vesselfreq$gam$residuals)
qqline(modelo1_vesselfreq$gam$residuals)

summary(modelo1_vesselfreq$gam)
summary(modelo2_vesselfreq$gam)
summary(modelo3_vesselfreq$gam)
summary(modelo4_vesselfreq$gam)
summary(modelo5_vesselfreq$gam)
summary(modelo6_vesselfreq$gam)
summary(modelo7_vesselfreq$gam)
sum(summary(modelo1_vesselfreq$gam)$s.table[, "edf"])
sum(summary(modelo2_vesselfreq$gam)$s.table[, "edf"])
sum(summary(modelo3_vesselfreq$gam)$s.table[, "edf"])
sum(summary(modelo4_vesselfreq$gam)$s.table[, "edf"])
sum(summary(modelo5_vesselfreq$gam)$s.table[, "edf"])
sum(summary(modelo6_vesselfreq$gam)$s.table[, "edf"])
sum(summary(modelo7_vesselfreq$gam)$s.table[, "edf"])

pred1 <- get_predictions(modelo1_vesselfreq$gam, 
                       cond = list(date1 = seq(min(Cortes_Qca_modelo$date1, na.rm=T),
                                            max(Cortes_Qca_modelo$date1, na.rm=T), 
                                            length.out = nrow(Cortes_Qca_modelo )),
                                  Tratam = c("Control", "Sequía"),
                                  se=T))

pred1$date <- as.Date(pred1$date1)

ggplot(data=pred1)+
  geom_line(mapping = aes(x=date, y=fit, color= Tratam), show.legend = F)+
  geom_ribbon(alpha=.4,mapping = aes(x=date, ymin=fit-CI, ymax=fit+CI, fill=Tratam), show.legend = T)+
  geom_point(data = Cortes_Qca_modelo, mapping =  aes(x=date, y=as.numeric(vessel_frequency_trans), color=Tratam), show.legend = F)+
  scale_color_manual(values = c("#1E90FF","#FF4040"))+
  scale_fill_manual(values = c("#97FFFF","#FF6A6A"))+
  theme(panel.background = element_rect(fill = "white"),
          axis.line.x = element_line(colour="black"),
          axis.line.y = element_line(colour="black"),
        axis.text = element_text(color = "black",size = 12),
        axis.ticks.length  = unit(0.1, "cm"))+
  scale_x_date(date_breaks = "2 month" ,date_labels = "%m")









```

```{r Modificacion Txemi_Escojo los vasos por fecha (hacer por fechas), include=FALSE}
path <-  c("C:/Minicores/Qca_Bruto/ImageJ/Tablas/c1-4-2021","C:/Minicores/Qca_Bruto/ImageJ/Tablas/d15-4-2021","C:/Minicores/Qca_Bruto/ImageJ/Tablas/e29-4-2021","C:/Minicores/Qca_Bruto/ImageJ/Tablas/f10-6-2021","C:/Minicores/Qca_Bruto/ImageJ/Tablas/g22-7-2021","C:/Minicores/Qca_Bruto/ImageJ/Tablas/h9-9-2021","C:/Minicores/Qca_Bruto/ImageJ/Tablas/i14-10-2021","C:/Minicores/Qca_Bruto/ImageJ/Tablas/j18-11-2021","C:/Minicores/Qca_Bruto/ImageJ/Tablas/k16-12-2021","C:/Minicores/Qca_Bruto/ImageJ/Tablas/l19-1-2022","C:/Minicores/Qca_Bruto/ImageJ/Tablas/m8-2-2022")

x <- 0
date_vess <- list("c1A21" = NA,"DD15A21"=NA,"e29Abr21" = NA, "f10J211" = NA, "g22J21"=NA,    "h9S21"=NA ,"i14O21"=NA, 
               "j18Nov21" = NA, "k16Dic21"=NA, "l19En22" = NA ,"m8Feb22" = NA)


while(x < length(path)){
  x <-  x +1
  setwd(path[x])
  name_documents <- list.files(pattern = '*.csv')
  docum <- lapply(name_documents, read_delim, delim = ',')
  names(docum) <- name_documents
  date_vess[[x]] <- docum
}
########una vez cargado todo, miro como va variando dependiendo de la diferencia de TRW, por lo cual elimino en cada fecha los vasos ya formados
##lo voy ha hacer por indv
##indv 2
date_vess$f10J211$a2QcC10J21.csv <- date_vess$f10J211$a2QcC10J21.csv[date_vess$f10J211$a2QcC10J21.csv$` ` != 1 | date_vess$f10J211$a2QcC10J21.csv$` ` != 2 | date_vess$f10J211$a2QcC10J21.csv$` ` != 3 | date_vess$f10J211$a2QcC10J21.csv$` ` != 4, ]

date_vess$g22J21$a2QcC22J21.csv[date_vess$g22J21$a2QcC22J21.csv$` ` == 2 | date_vess$g22J21$a2QcC22J21.csv$` ` ==  4 , ]

date_vess$h9S21$`2QcC9S21.csv` <- date_vess$h9S21$`2QcC9S21.csv`[date_vess$h9S21$`2QcC9S21.csv`$` ` == 5 | date_vess$h9S21$`2QcC9S21.csv`$` ` ==  7 | date_vess$h9S21$`2QcC9S21.csv`$` ` ==  8 | date_vess$h9S21$`2QcC9S21.csv`$` ` ==  11 | date_vess$h9S21$`2QcC9S21.csv`$` ` ==  14 | date_vess$h9S21$`2QcC9S21.csv`$` ` ==  16 | date_vess$h9S21$`2QcC9S21.csv`$` ` ==  17 | date_vess$h9S21$`2QcC9S21.csv`$` ` ==  19  | date_vess$h9S21$`2QcC9S21.csv`$` ` ==  20  | date_vess$h9S21$`2QcC9S21.csv`$` ` ==  21  | date_vess$h9S21$`2QcC9S21.csv`$` ` ==  23 | date_vess$h9S21$`2QcC9S21.csv`$` ` ==   24 , ]

date_vess$i14O21$a2QcC14O21.csv <- NULL

date_vess$j18Nov21$a2QcC18N21.csv <- date_vess$j18Nov21$a2QcC18N21.csv [date_vess$j18Nov21$a2QcC18N21.csv$` ` == 1 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==  2 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==  3 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==  5 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==  6 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==  8 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==  9 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==  10   | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==  11 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==  13 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==  14 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==   17  | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==   18 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==   22 
 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==   27 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==   23 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==   21 
 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==   25 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==   29 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==   26 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==   31 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==   32 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==   33 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==   35 | date_vess$j18Nov21$a2QcC18N21.csv$` ` ==   34 , ]


date_vess$k16Dic21$`2QcC16D21.csv` <- date_vess$k16Dic21$`2QcC16D21.csv` [date_vess$k16Dic21$`2QcC16D21.csv` $` ` == 1 | date_vess$k16Dic21$`2QcC16D21.csv` $` ` ==  4 | date_vess$k16Dic21$`2QcC16D21.csv` $` ` ==  9 | date_vess$k16Dic21$`2QcC16D21.csv` $` ` ==  8 | date_vess$k16Dic21$`2QcC16D21.csv` $` ` ==  7 | date_vess$k16Dic21$`2QcC16D21.csv` $` ` ==  14 | date_vess$k16Dic21$`2QcC16D21.csv` $` ` ==  12 | date_vess$k16Dic21$`2QcC16D21.csv` $` ` ==  13   | date_vess$k16Dic21$`2QcC16D21.csv` $` ` ==  20 | date_vess$k16Dic21$`2QcC16D21.csv` $` ` ==  27 | date_vess$k16Dic21$`2QcC16D21.csv` $` ` ==  28 | date_vess$k16Dic21$`2QcC16D21.csv` $` ` ==   25  | date_vess$k16Dic21$`2QcC16D21.csv` $` ` ==   24, ]

date_vess$l19En22$a2QcC19E22.csv <- date_vess$l19En22$a2QcC19E22.csv [date_vess$l19En22$a2QcC19E22.csv$` ` == 8 | date_vess$l19En22$a2QcC19E22.csv $` ` ==  7 | date_vess$l19En22$a2QcC19E22.csv $` ` ==  15 | date_vess$l19En22$a2QcC19E22.csv $` ` ==  20 | date_vess$l19En22$a2QcC19E22.csv $` ` ==  23 | date_vess$l19En22$a2QcC19E22.csv $` ` ==  26 | date_vess$l19En22$a2QcC19E22.csv $` ` ==  27 | date_vess$l19En22$a2QcC19E22.csv $` ` ==  30   | date_vess$l19En22$a2QcC19E22.csv $` ` ==  34 | date_vess$l19En22$a2QcC19E22.csv $` ` ==  37 | date_vess$l19En22$a2QcC19E22.csv $` ` ==  40 | date_vess$l19En22$a2QcC19E22.csv $` ` ==   44, ]


date_vess$m8Feb22$a2QcC2F22.csv <- NULL

###indv3

date_vess$e29Abr21$b3QcC29A21.csv <- date_vess$e29Abr21$b3QcC29A21.csv[date_vess$e29Abr21$b3QcC29A21.csv$` ` == 3 | date_vess$e29Abr21$b3QcC29A21.csv$` ` == 2, ]



date_vess$f10J211$b3QcC10J21.csv <- date_vess$f10J211$b3QcC10J21.csv[date_vess$f10J211$b3QcC10J21.csv$` ` == 1 | date_vess$f10J211$b3QcC10J21.csv$` ` == 2 | date_vess$f10J211$b3QcC10J21.csv$` ` == 3 | date_vess$f10J211$b3QcC10J21.csv$` ` ==  5 | date_vess$f10J211$b3QcC10J21.csv$` ` ==  6 | date_vess$f10J211$b3QcC10J21.csv$` ` ==  7 | date_vess$f10J211$b3QcC10J21.csv$` ` ==  8, ]

date_vess$g22J21$b3QcC22J21.csv <- date_vess$g22J21$b3QcC22J21.csv[date_vess$g22J21$b3QcC22J21.csv$` ` == 1 | date_vess$g22J21$b3QcC22J21.csv$` ` ==  2 | date_vess$g22J21$b3QcC22J21.csv$` ` ==  4 | date_vess$g22J21$b3QcC22J21.csv$` ` ==  6 | date_vess$g22J21$b3QcC22J21.csv$` ` ==  9 | date_vess$g22J21$b3QcC22J21.csv$` ` ==  16 | date_vess$g22J21$b3QcC22J21.csv$` ` ==  12 | date_vess$g22J21$b3QcC22J21.csv$` ` ==  8 | date_vess$g22J21$b3QcC22J21.csv$` ` ==  7 | date_vess$g22J21$b3QcC22J21.csv$` ` ==  13 | date_vess$g22J21$b3QcC22J21.csv$` ` ==  21 | date_vess$g22J21$b3QcC22J21.csv$` ` ==  22 | date_vess$g22J21$b3QcC22J21.csv$` ` ==  23 | date_vess$g22J21$b3QcC22J21.csv$` ` ==  24, ]

date_vess$h9S21$`3QcC9S21.csv` <- date_vess$h9S21$`3QcC9S21.csv`[date_vess$h9S21$`3QcC9S21.csv`$` ` == 5 | date_vess$h9S21$`3QcC9S21.csv`$` ` ==  16 | date_vess$h9S21$`3QcC9S21.csv`$` ` ==  18 | date_vess$h9S21$`3QcC9S21.csv`$` ` ==  25 | date_vess$h9S21$`3QcC9S21.csv`$` ` ==  26 | date_vess$h9S21$`3QcC9S21.csv`$` ` ==  28 | date_vess$h9S21$`3QcC9S21.csv`$` ` ==  29 | date_vess$h9S21$`3QcC9S21.csv`$` ` ==  32  | date_vess$h9S21$`3QcC9S21.csv`$` ` ==  34  | date_vess$h9S21$`3QcC9S21.csv`$` ` ==  41  | date_vess$h9S21$`3QcC9S21.csv`$` ` ==  43 | date_vess$h9S21$`3QcC9S21.csv`$` ` ==   47 | date_vess$h9S21$`3QcC9S21.csv`$` ` ==   48 | date_vess$h9S21$`3QcC9S21.csv`$` ` ==   49 | date_vess$h9S21$`3QcC9S21.csv`$` ` ==   49 , ]

date_vess$i14O21$b3QcC14O21.csv <- date_vess$i14O21$b3QcC14O21.csv[date_vess$i14O21$b3QcC14O21.csv$` ` == 1 | date_vess$i14O21$b3QcC14O21.csv$` ` ==  2 | date_vess$i14O21$b3QcC14O21.csv$` ` ==  5 | date_vess$i14O21$b3QcC14O21.csv$` ` ==  4 | date_vess$i14O21$b3QcC14O21.csv$` ` ==  3 | date_vess$i14O21$b3QcC14O21.csv$` ` ==  11 | date_vess$i14O21$b3QcC14O21.csv$` ` ==  9 | date_vess$i14O21$b3QcC14O21.csv$` ` ==  23  | date_vess$i14O21$b3QcC14O21.csv$` ` ==  25  | date_vess$i14O21$b3QcC14O21.csv$` ` ==  21  | date_vess$i14O21$b3QcC14O21.csv$` ` ==  18 | date_vess$i14O21$b3QcC14O21.csv$` ` ==   17 | date_vess$i14O21$b3QcC14O21.csv$` ` ==   20 | date_vess$i14O21$b3QcC14O21.csv$` ` ==   19, ]

date_vess$j18Nov21$b3QcC18N21.csv <- NULL


date_vess$k16Dic21$`3QcC16D21.csv` <- date_vess$k16Dic21$`3QcC16D21.csv` [date_vess$k16Dic21$`3QcC16D21.csv` $` ` == 4 | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==   3| date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==  1 | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==  9 | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==  7 | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==  15 | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==  14 | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==  18   | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==  19 | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==  21 | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==  23 | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==   22  | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==   27 | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==   30  | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==   38 | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==   34  | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==   33 | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==   43  | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==   46  | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==   39  | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==   37 | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==   31  | date_vess$k16Dic21$`3QcC16D21.csv` $` ` ==   35, ]

date_vess$l19En22$b3QcC19E22.csv <- NULL


date_vess$m8Feb22$b3QcC2F22.csv <- NULL


###indv5

date_vess$e29Abr21$c5QcC29A21.csv <- date_vess$e29Abr21$c5QcC29A21.csv[date_vess$e29Abr21$c5QcC29A21.csv$` ` == 1 | date_vess$e29Abr21$c5QcC29A21.csv$` ` == 3, ]



date_vess$f10J211$c5QcC10J21.csv <- NULL

date_vess$g22J21$c5QcC22J21.csv <- date_vess$g22J21$c5QcC22J21.csv[date_vess$g22J21$c5QcC22J21.csv$` ` == 1 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  2 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  3 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  8 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  7 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  4 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  6 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  10 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  12 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  13 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  14 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  15 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  17 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  19 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  21 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  22 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  20 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  18 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  24 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  23 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  27 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  28 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  29 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  32 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  36 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  37 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  34 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  35 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  31 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  33 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  40 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  41 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  42 | date_vess$g22J21$c5QcC22J21.csv$` ` ==  38, ]

date_vess$h9S21$`5QcC9S21.csv` <- NULL

date_vess$l19En22$c5QcC19E22.csv <-   date_vess$l19En22$c5QcC19E22.csv[date_vess$l19En22$c5QcC19E22.csv$` ` == 2 | date_vess$l19En22$c5QcC19E22.csv$` ` ==  5 | date_vess$l19En22$c5QcC19E22.csv$` ` ==  8 | date_vess$l19En22$c5QcC19E22.csv$` ` ==  7 | date_vess$l19En22$c5QcC19E22.csv$` ` ==   9 | date_vess$l19En22$c5QcC19E22.csv$` ` ==  12 | date_vess$l19En22$c5QcC19E22.csv$` ` ==  14 | date_vess$l19En22$c5QcC19E22.csv$` ` ==  16 | date_vess$l19En22$c5QcC19E22.csv$` ` ==  17 | date_vess$l19En22$c5QcC19E22.csv$` ` ==  21 | date_vess$l19En22$c5QcC19E22.csv$` ` ==  22 | date_vess$l19En22$c5QcC19E22.csv$` ` ==  23 | date_vess$l19En22$c5QcC19E22.csv$` ` ==  27 | date_vess$l19En22$c5QcC19E22.csv$` ` ==  30 | date_vess$l19En22$c5QcC19E22.csv$` ` ==  34 | date_vess$l19En22$c5QcC19E22.csv$` ` ==  35, ]


date_vess$m8Feb22$c5QcC2F22.csv <- NULL

##indv8


date_vess$f10J211$d8QcC10J21.csv <- date_vess$f10J211$d8QcC10J21.csv[date_vess$f10J211$d8QcC10J21.csv$` ` == 1 | date_vess$f10J211$d8QcC10J21.csv$` ` == 2 | date_vess$f10J211$d8QcC10J21.csv$` ` == 3 | date_vess$f10J211$d8QcC10J21.csv$` ` ==  4 | date_vess$f10J211$d8QcC10J21.csv$` ` ==  6 | date_vess$f10J211$d8QcC10J21.csv$` ` ==  7 | date_vess$f10J211$d8QcC10J21.csv$` ` ==  8 | date_vess$f10J211$d8QcC10J21.csv$` ` ==  10 | date_vess$f10J211$d8QcC10J21.csv$` ` ==  11, ]

date_vess$g22J21$d8QcC22J21.csv <- date_vess$g22J21$d8QcC22J21.csv[date_vess$g22J21$d8QcC22J21.csv$` ` == 5 | date_vess$g22J21$d8QcC22J21.csv$` ` ==  7 | date_vess$g22J21$d8QcC22J21.csv$` ` ==  11 | date_vess$g22J21$d8QcC22J21.csv$` ` ==  12 | date_vess$g22J21$d8QcC22J21.csv$` ` ==  14 | date_vess$g22J21$d8QcC22J21.csv$` ` ==  15 | date_vess$g22J21$d8QcC22J21.csv$` ` ==  16 | date_vess$g22J21$d8QcC22J21.csv$` ` ==  19 | date_vess$g22J21$d8QcC22J21.csv$` ` ==  21 | date_vess$g22J21$d8QcC22J21.csv$` ` ==  24 | date_vess$g22J21$d8QcC22J21.csv$` ` ==  25 | date_vess$g22J21$d8QcC22J21.csv$` ` ==  27, ]

date_vess$h9S21$`8QcC9S21.csv` <- NULL

date_vess$i14O21$c8QcC14O21.csv <- NULL

date_vess$j18Nov21$c8QcC18N21.csv <-  date_vess$g22J21$c8QcC18N21.csv[date_vess$g22J21$c8QcC18N21.csv$` ` == 5 | date_vess$g22J21$c8QcC18N21.csv$` ` ==  7 | date_vess$g22J21$c8QcC18N21.csv$` ` ==  11 | date_vess$g22J21$c8QcC18N21.csv$` ` ==  12 | date_vess$g22J21$c8QcC18N21.csv$` ` ==  14 | date_vess$g22J21$c8QcC18N21.csv$` ` ==  15 | date_vess$g22J21$c8QcC18N21.csv$` ` ==  16 | date_vess$g22J21$c8QcC18N21.csv$` ` ==  19 | date_vess$g22J21$c8QcC18N21.csv$` ` ==  21 | date_vess$g22J21$c8QcC18N21.csv$` ` ==  24 | date_vess$g22J21$c8QcC18N21.csv$` ` ==  25 | date_vess$g22J21$c8QcC18N21.csv$` ` ==  27, ]


date_vess$k16Dic21$`8QcC16D21.csv` <- date_vess$k16Dic21$`8QcC16D21.csv` [date_vess$k16Dic21$`8QcC16D21.csv` $` ` == 7 | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   6| date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==  9 | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==  8 | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==  12 | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==  17 | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==  18 | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==  15   | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==  22 | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==  33 | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==  35 | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   37  | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   43 | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   47  | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   46 | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   55  | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   57 | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   59  | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   67  | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   65  | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   66 | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   70  | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   71 | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   74  | date_vess$k16Dic21$`8QcC16D21.csv` $` ` ==   73, ]




date_vess$m8Feb22$d8QcC2F22.csv <- NULL

##indv9

date_vess$DD15A21$b9QcC15A21s.csv <- date_vess$DD15A21$b9QcC15A21s.csv[date_vess$DD15A21$b9QcC15A21s.csv$` ` == 1 | date_vess$DD15A21$b9QcC15A21s.csv$` ` == 2, ]

date_vess$e29Abr21$d9QcC29A21.csv  <- date_vess$e29Abr21$d9QcC29A21.csv[date_vess$e29Abr21$d9QcC29A21.csv$` ` == 2 | date_vess$e29Abr21$d9QcC29A21.csv$` ` == 3, ]

date_vess$f10J211$g9QcC10J21.csv <- NULL

quitar <- c(1,22,7,19)
date_vess$g22J21$e9QcC22J21.csv <- date_vess$g22J21$e9QcC22J21.csv[!date_vess$g22J21$e9QcC22J21.csv$` ` %in% quitar , ]

poner <- c(1,10,12,20,21,18)
date_vess$h9S21$`9QcC9S21.csv` <- date_vess$h9S21$`9QcC9S21.csv`[date_vess$h9S21$`9QcC9S21.csv`$` ` %in% poner , ]

poner <- c(5,8,10,12,14,17,19,22,25)
date_vess$i14O21$d9QcC14O21.csv <-  date_vess$i14O21$d9QcC14O21.csv[date_vess$i14O21$d9QcC14O21.csv$` ` %in% poner , ]

date_vess$j18Nov21$d9QcC18N21.csv <- NULL

date_vess$l19En22$d9QcC19E22.csv <- NULL


#indv10

date_vess$e29Abr21$e10QcC29A21.csv <- NULL
date_vess$f10J211$h10QcC10J21.csv <- NULL

date_vess$DD15A21$b9QcC15A21s.csv <- date_vess$DD15A21$b9QcC15A21s.csv[date_vess$DD15A21$b9QcC15A21s.csv$` ` == 1 | date_vess$DD15A21$b9QcC15A21s.csv$` ` == 2, ]

quitar <- c(1,3,12,45,36,28)
date_vess$g22J21$f10QcC22J21.csv <- date_vess$g22J21$f10QcC22J21.csv[!date_vess$g22J21$f10QcC22J21.csv$` ` %in% quitar , ]


date_vess$h9S21$`10QcC9S21.csv` <- NULL

poner <- c(3,8,9,12,10,11,15,13,16,17,21,22,23,25,31,35,38)
date_vess$i14O21$h10QcC14O21.csv <-  date_vess$i14O21$h10QcC14O21.csv[date_vess$i14O21$h10QcC14O21.csv$` ` %in% poner , ]

date_vess$j18Nov21$e10QcC18N21.csv <- NULL

poner <- c(2,3,5,9,14,16,18,22,24,25,26)
date_vess$k16Dic21$`10QcC16D21.csv` <-  date_vess$k16Dic21$`10QcC16D21.csv`[date_vess$k16Dic21$`10QcC16D21.csv`$` ` %in% poner , ]

date_vess$l19En22$e10QcC19E22.csv <- NULL
date_vess$m8Feb22$h10QcC2F22.csv <- NULL

#indv18


date_vess$DD15A21$d18QcS15A21.csv <- NULL
date_vess$e29Abr21$f18QcS29A21.csv <- NULL


quitar <- c(1,7,5,6)
date_vess$f10J211$i18QcS10J21.csv <- date_vess$f10J211$i18QcS10J21.csv[!date_vess$f10J211$i18QcS10J21.csv$` ` %in% quitar , ]

poner <- c(2,4,7,5,3,1,14,17,22,28,25,27,24,16,10,8,13)
date_vess$g22J21$g18QcS22J21.csv <-  date_vess$g22J21$g18QcS22J21.csv [date_vess$g22J21$g18QcS22J21.csv$` ` %in% poner , ]

date_vess$h9S21$`18QcS9S21.csv` <- NULL

poner <- c(20,21,19,18,17,23,24,10,14,9,2,7)
date_vess$i14O21$i18QcS14O21.csv <-  date_vess$i14O21$i18QcS14O21.csv[date_vess$i14O21$i18QcS14O21.csv$` ` %in% poner , ]

date_vess$j18Nov21$e10QcC18N21.csv <- NULL


date_vess$k16Dic21$`18QcS16D21.csv` <- NULL

poner <- c(2,3,5,12,4,9,14,6,33,34,28,25,27,30)
date_vess$l19En22$h18QcS19E22.csv <- date_vess$l19En22$h18QcS19E22.csv[date_vess$l19En22$h18QcS19E22.csv$` ` %in% poner , ]

##indv19

date_vess$DD15A21$e19QcS15A21.csv <- NULL

quitar <- c(1)
date_vess$e29Abr21$g19QcS29A21.csv <-  date_vess$e29Abr21$g19QcS29A21.csv[!date_vess$e29Abr21$g19QcS29A21.csv$` ` %in% quitar , ]


quitar <- c(1,6,8,14,17,19)
date_vess$f10J211$j19QcS10J21.csv <- date_vess$f10J211$j19QcS10J21.csv[!date_vess$f10J211$j19QcS10J21.csv$` ` %in% quitar , ]

poner <- c(2,7,13,20,24,12,18,9,5,4,17,26,3,10)
date_vess$g22J21$h19QcS22J21.csv <-  date_vess$g22J21$h19QcS22J21.csv [date_vess$g22J21$h19QcS22J21.csv$` ` %in% poner , ]

poner <- c(2,8,11,15,19,22,26,27,28)
date_vess$j18Nov21$g19QcS18N21.csv <- date_vess$j18Nov21$g19QcS18N21.csv [date_vess$j18Nov21$g19QcS18N21.csv$` ` %in% poner , ]

poner <- c(10,17,30,43,45,41,54)
date_vess$k16Dic21$`19QcS16D21.csv` <- date_vess$k16Dic21$`19QcS16D21.csv` [date_vess$k16Dic21$`19QcS16D21.csv`$` ` %in% poner , ]

date_vess$l19En22$i19QcS19E22.csv <- NULL

poner <- c(28,27,24,44,45)
date_vess$m8Feb22$i19QcS2F22.csv <- date_vess$m8Feb22$i19QcS2F22.csv [date_vess$m8Feb22$i19QcS2F22.csv$` ` %in% poner , ]

##indv26

date_vess$DD15A21$f26QcS15A21.csv <- NULL

date_vess$e29Abr21$h26QcS29A21.csv <- NULL

quitar <- c(1,2,4)
date_vess$h9S21$`26QsS9S21.csv` <- date_vess$h9S21$`26QsS9S21.csv`[!date_vess$h9S21$`26QsS9S21.csv`$` ` %in% quitar , ]


date_vess$i14O21$j26QcS14O21.csv <- NULL

###indv30

quitar <- c(3)
date_vess$e29Abr21$i30QcS29A21.csv <-  date_vess$e29Abr21$i30QcS29A21.csv[!date_vess$e29Abr21$i30QcS29A21.csv$` ` %in% quitar , ]

quitar <- c(1,5)
date_vess$f10J211$k30QcS10J21.csv <- date_vess$f10J211$k30QcS10J21.csv[!date_vess$f10J211$k30QcS10J21.csv$` ` %in% quitar , ]

quitar <- c(1,2,3,6,9,11,20,27,31,38,17,22,26,33,42,45)
date_vess$g22J21$j30QcS22J21.csv <-  date_vess$g22J21$j30QcS22J21.csv [!date_vess$g22J21$j30QcS22J21.csv$` ` %in% quitar , ]

poner <- c(1,2,6,7,12)
date_vess$h9S21$`30QsS9S21.csv` <- date_vess$h9S21$`30QsS9S21.csv` [date_vess$h9S21$`30QsS9S21.csv`$` ` %in% poner , ]

date_vess$i14O21$k30QcS14O21.csv <- NULL

date_vess$j18Nov21$h30QcS18N21.csv <- NULL

poner <- c(3,10,17,25)
date_vess$k16Dic21$`30QcS16D21.csv` <- date_vess$k16Dic21$`30QcS16D21.csv` [date_vess$k16Dic21$`30QcS16D21.csv`$` ` %in% poner , ]


date_vess$l19En22$j30QcS19E22.csv <- NULL

poner <- c(10,15,19,22,26,27,33,39,44,46,42,47,51,56,55,57)
date_vess$m8Feb22$j30QcS2F22.csv <- date_vess$m8Feb22$j30QcS2F22.csv [date_vess$m8Feb22$j30QcS2F22.csv$` ` %in% poner , ]

###indv36

quitar <- c(2,3,5)
date_vess$e29Abr21$j36QcC29A21.csv <-  date_vess$e29Abr21$j36QcC29A21.csv[!date_vess$e29Abr21$j36QcC29A21.csv$` ` %in% quitar , ]


quitar <- c(6,11,12,16,17)
date_vess$g22J21$k36QcC22J21.csv <-  date_vess$g22J21$k36QcC22J21.csv [!date_vess$g22J21$k36QcC22J21.csv$` ` %in% quitar , ]

poner <- c(3,6,5,7,11,16)
date_vess$h9S21$`36QsC9S21.csv` <- date_vess$h9S21$`36QsC9S21.csv` [date_vess$h9S21$`36QsC9S21.csv`$` ` %in% poner , ]


poner <- c(7,8,9,12,14,15,21,25,23,22,31,35,30,32,27,29,33,34)
date_vess$i14O21$l36QcC14O21.csv <- date_vess$i14O21$l36QcC14O21.csv [date_vess$i14O21$l36QcC14O21.csv$` ` %in% poner , ]

date_vess$j18Nov21$i36QcC18N21.csv <-  NULL

date_vess$k16Dic21$`36QcC16D21.csv` <- NULL

date_vess$l19En22$k36QcC19E22.csv <- NULL

###indv40

quitar <- c(1,2,5)
date_vess$f10J211$l40QcC10J21.csv <-  date_vess$f10J211$l40QcC10J21.csv [!date_vess$f10J211$l40QcC10J21.csv$` ` %in% quitar , ]

poner <- c(1,4,9,10,11,16,20,22,24,26,28,31,35,39,38,40,42)
date_vess$g22J21$l40QcC22J21.csv <-  date_vess$g22J21$l40QcC22J21.csv [date_vess$g22J21$l40QcC22J21.csv$` ` %in% poner , ]


date_vess$h9S21$`40QsC9S21.csv` <- NULL

poner <- c(9,12,16,18,20,22)
date_vess$i14O21$m40QcC14O21.csv <- date_vess$i14O21$m40QcC14O21.csv [date_vess$i14O21$m40QcC14O21.csv$` ` %in% poner , ]

date_vess$j18Nov21$j40cC18N21.csv <-  NULL

poner <- c(3,4,21)
date_vess$l19En22$m40QcC19E22.csv <- date_vess$l19En22$m40QcC19E22.csv [date_vess$l19En22$m40QcC19E22.csv$` ` %in% poner , ]

poner <- c(13,17,23)
date_vess$m8Feb22$k40QcC2F22.csv <- date_vess$m8Feb22$k40QcC2F22.csv [date_vess$m8Feb22$k40QcC2F22.csv$` ` %in% poner , ]

###indv44


quitar <- c(1,2,5,6)
date_vess$f10J211$m44QcC10J21.csv <-  date_vess$f10J211$m44QcC10J21.csv [!date_vess$f10J211$m44QcC10J21.csv$` ` %in% quitar , ]

quitar <- c(1,6,8,10,12,13,17,18,19,26,22,25,27,29,32)
date_vess$g22J21$m44QcC22J21.csv <-  date_vess$g22J21$m44QcC22J21.csv [!date_vess$g22J21$m44QcC22J21.csv$` ` %in% quitar , ]


poner <- c(1,2,3,4,5,6,8,12,14,18,22,20,24,25,27,31,35,32,39,41,44,45,47)
date_vess$h9S21$`44QsC9S21.csv` <- date_vess$h9S21$`44QsC9S21.csv` [date_vess$h9S21$`44QsC9S21.csv`$` ` %in% poner , ]

date_vess$k16Dic21$`44QcC16D21.csv` <- NULL

poner <- c(1,4,6,9,11,12,19,17,21,25,45)
date_vess$l19En22$n44QcC19E22.csv <- date_vess$l19En22$n44QcC19E22.csv [date_vess$l19En22$n44QcC19E22.csv$` ` %in% poner , ]

date_vess$m8Feb22$l44QcC2F22.csv <- NULL

###indv47

date_vess$c1A21$h47QcS1A21.csv <- NULL

date_vess$e29Abr21$m47QcS29A21.csv <- NULL

quitar <- c(12,13,14,9,18,3)
date_vess$f10J211$n47QcS10J21.csv <-  date_vess$f10J211$n47QcS10J21.csv [!date_vess$f10J211$n47QcS10J21.csv$` ` %in% quitar , ]

poner <- c(26,7,2,19,5,9,18,24,25,20,13,11,4,22)
date_vess$g22J21$n47QcS22J21.csv <-  date_vess$g22J21$n47QcS22J21.csv [date_vess$g22J21$n47QcS22J21.csv$` ` %in% poner , ]

date_vess$h9S21$`47QsS9S21.csv` <- NULL

poner <- c(13,14,31,37,38)
date_vess$i14O21$n47QcS14O21.csv <-  date_vess$i14O21$n47QcS14O21.csv [date_vess$i14O21$n47QcS14O21.csv$` ` %in% poner , ]

date_vess$j18Nov21$k47cS18N21.csv <- NULL

poner <- c(1,2,3,6,7,8,9,11,12,14,18)
date_vess$k16Dic21$`47QcS16D21.csv` <-  date_vess$k16Dic21$`47QcS16D21.csv` [date_vess$k16Dic21$`47QcS16D21.csv`$` ` %in% poner , ]

date_vess$l19En22$o47QcS19E22.csv <- NULL

###indv52


date_vess$e29Abr21$n52QcS29A21.csv <- NULL

quitar <- c(1,3,4,6,7,9,10)
date_vess$g22J21$o52QcS22J21.csv <-  date_vess$g22J21$o52QcS22J21.csv [!date_vess$g22J21$o52QcS22J21.csv$` ` %in% quitar , ]

poner <- c(3,6,8,12,13,20,23,24)
date_vess$i14O21$o52QcS14O21.csv <-  date_vess$i14O21$o52QcS14O21.csv [date_vess$i14O21$o52QcS14O21.csv$` ` %in% poner , ]

poner <- c(3,5,7,9,12,14,22,23,24,25)
date_vess$k16Dic21$`52QcS16D21.csv` <-  date_vess$k16Dic21$`52QcS16D21.csv` [date_vess$k16Dic21$`52QcS16D21.csv`$` ` %in% poner , ]

poner <- c(3,11,12,14,19,26)
date_vess$l19En22$r52QcS19E22.csv <- date_vess$l19En22$r52QcS19E22.csv[date_vess$l19En22$r52QcS19E22.csv$` ` %in% poner , ]

date_vess$m8Feb22$m52QcS2F22.csv <- NULL


```

```{r Modificacion Txemi, include=FALSE}

area_porvaso <- lapply(date_vess, function(x){
  lapply(x, function(z){z$area_Feret <- 0.785*(z$Feret^2)
  return(z)})
  
})

names(area_porvaso) <- ifelse(names(area_porvaso) =="g22J21", "g22Jul21", names(area_porvaso))
names(area_porvaso) <- ifelse(names(area_porvaso) =="DD15A21", "D15A21", names(area_porvaso))
names(area_porvaso) <- ifelse(names(area_porvaso) =="e29Abr21", "e29A21", names(area_porvaso))
names(area_porvaso) <- ifelse(names(area_porvaso) =="f10J211", "f10J21", names(area_porvaso))


meses <- c(
  A = 4 , J = 6, Jul = 7, S = 9,
  O = 10, Nov = 11, Dic = 12, En = 1, Feb = 2)

extraer_fecha <- function(codigo) {
  
  # Extraer día
  dia <- as.numeric(str_extract(codigo, "\\d+"))
  
  # Extraer la parte de mes y año (lo que queda después del día)
  resto <- str_extract(codigo, "[A-Za-z]+\\d+$")
  
  # Separar mes y año
  mes_str <- str_extract(resto, "[A-Za-z]+")
  ano_str <- str_extract(resto, "\\d+")
  
  # Buscar el mes en el vector meses
  mes_num <- meses[mes_str]
  
  # Año (por si acaso tiene 2 o más dígitos)
  
  # Crear fecha
  date_char <- paste(paste("20",ano_str, sep = "") ,mes_num, dia, sep = "/")
  return(date_char)
} ###extraigo la fecha por el nombre

fechas <- as.character(names(area_porvaso))
fechas <- sapply(fechas, extraer_fecha)
fechas <-  as.Date.character(fechas)

x <- 0 
while(x < length(area_porvaso)){
  x <- x +1
  date <- fechas[x]
  y <- 0
  while(y < length(area_porvaso[[x]])){
    y <- y+1
    area_porvaso[[x]][[y]]$fecha <- date
  }
  rm(y)
} ##le añado la fecha
rm(x)

##añadimos el individuo
extraer_individuo <- function(nombre) {
  num <- regmatches(nombre, regexpr("[0-9]+", nombre))  # Busca el primer número
  as.numeric(num)}

area_porvaso <- lapply(area_porvaso, function(df){
  nombres <- names(df)
  individuos <- sapply(nombres, extraer_individuo)
  z <- 0
  while(z < length(df)){
    z <- z+1
    df[[z]]$indv <- individuos[z]
  }
  df <- lapply(df, function(y){
  y <- data_frame("area_Feret "= y$area_Feret, "fecha" = y$fecha, "indv" = y$indv)
  return(y)
  })
  return(df)
}) ##creo el data frame con el indiviuo y las variables que necesito

###voy a aliminar las ventanas temporales de mas de 1 mes
area_porvaso$i14O21$m40QcC14O21.csv <- NULL
area_porvaso$i14O21$i18QcS14O21.csv <- NULL
area_porvaso$i14O21$h10QcC14O21.csv <- NULL
area_porvaso$k16Dic21$`8QcC16D21.csv` <- NULL
area_porvaso$l19En22$n44QcC19E22.csv <- NULL
area_porvaso$i14O21$o52QcS14O21.csv <- NULL


area_porvaso_unido <- do.call(rbind, Map(data.frame, lapply(area_porvaso, function(x){ do.call(rbind, Map(data.frame, x))})))

control <- c(2,3,5,8,9,10,36,40,44)
area_porvaso_unido$treatment <- ifelse(area_porvaso_unido$indv %in% control, "control", "drought")

area_porvaso_unido$area_Feret. <-  ifelse(area_porvaso_unido$fecha == as.Date("2021-04-29
") & area_porvaso_unido$indv == 40, NA, area_porvaso_unido$area_Feret. )

area_porvaso_unido$area_Feret. <-  ifelse(area_porvaso_unido$fecha == as.Date("2021-11-18") & area_porvaso_unido$area_Feret. >0.01 , NA, area_porvaso_unido$area_Feret. ) ##vasos de la fecha anterior


Total_areavessel <- ggplot(area_porvaso_unido, aes(x= as.factor(fecha), y= area_Feret., fill= as.factor(treatment)))+
           geom_boxplot()+
  theme_classic()+
  ylab("area por vaso (mm^2)")+
  scale_fill_manual(values = c("#97FFFF","#FF6A6A"))


area_porvaso_unido_sinEW <- area_porvaso_unido
area_porvaso_unido_sinEW$fecha <- ifelse(area_porvaso_unido_sinEW$fecha == as.Date("2021-04-01") | area_porvaso_unido_sinEW$fecha == as.Date("2021-04-15") | area_porvaso_unido_sinEW$fecha == as.Date("2021-04-29"), NA, area_porvaso_unido_sinEW$fecha )

area_porvaso_unido_sinEW <- area_porvaso_unido_sinEW[complete.cases(area_porvaso_unido_sinEW), ]

LW_areavessel <- ggplot(area_porvaso_unido_sinEW, aes(x= as.factor(fecha), y= area_Feret., fill= as.factor(treatment)))+
           geom_boxplot(show.legend = F)+
  theme(panel.background = element_rect(fill = "white"),
          axis.line.x = element_line(colour="black"),
          axis.line.y = element_line(colour="black"),
        axis.text = element_text(color = "black",size = 12),
        axis.ticks.length  = unit(0.1, "cm"))+
  ylab(" ")+
  scale_fill_manual(values = c("#97FFFF","#FF6A6A"))+
  scale_y_continuous(limits = c(0,0.02))+
  xlab("date")


area_porvaso_unido_EW <- area_porvaso_unido
area_porvaso_unido_EW$fecha <- ifelse(area_porvaso_unido_EW$fecha == as.Date("2021-04-01") | area_porvaso_unido_EW$fecha == as.Date("2021-04-15") | area_porvaso_unido_EW$fecha == as.Date("2021-04-29"), area_porvaso_unido_EW$fecha,  NA )
area_porvaso_unido_EW <- area_porvaso_unido_EW[complete.cases(area_porvaso_unido_EW), ]

EW_areavessel <- ggplot(area_porvaso_unido_EW, aes(x= as.factor(fecha), y= area_Feret., fill= as.factor(treatment)))+
           geom_boxplot(show.legend = F)+
  theme(panel.background = element_rect(fill = "white"),
          axis.line.x = element_line(colour="black"),
          axis.line.y = element_line(colour="black"),
        axis.text = element_text(color = "black",size = 12),
        axis.ticks.length  = unit(0.1, "cm"))+
  ylab(" ")+
  scale_fill_manual(values = c("#97FFFF","#FF6A6A"))+
  scale_y_continuous()+
  xlab("date")


ggplot(area_porvaso_unido, aes(x= fecha, y= area_Feret., color = treatment))+
           geom_point()+
  geom_smooth()+
  theme_classic()+
  ylab("area por vaso (mm^2)")+
  scale_fill_manual(values = c("#97FFFF","#FF6A6A"))+
  scale_color_manual(values = c("#1E90FF","#FF4040"))



area_porvaso_unido$area_Feret_mod <- log(area_porvaso_unido$area_Feret.)
area_porvaso_unido$date1 <- as.numeric(area_porvaso_unido$fecha)
##########por aqui

area_porvaso_unido_DBH <- merge(area_porvaso_unido, DBH_H, by= c("indv","indv"))

area_porvaso_unido_DBH$DBH_cm  <- area_porvaso_unido_DBH$`DBH_(cm)` 
area_porvaso_unido_DBH$Diametro_copa_cm <- area_porvaso_unido_DBH$`Diametro_copa_(cm)`

trend_areaves1 <- gamm4(data =area_porvaso_unido_DBH, area_Feret. ~ s(date1) + treatment , random=~(1|indv))
trend_areaves2 <- gamm4(data =area_porvaso_unido_DBH, area_Feret. ~ s(date1) + s(DBH_cm) , random=~(1|indv))
trend_areaves3 <- gamm4(data =area_porvaso_unido_DBH, area_Feret. ~ s(date1) +   s(Diametro_copa_cm) , random=~(1|indv))
trend_areaves4 <- gamm4(data =area_porvaso_unido_DBH, area_Feret. ~ s(date1) + s(DBH_cm) + treatment , random=~(1|indv))
trend_areaves4 <- gamm4(data =area_porvaso_unido_DBH, area_Feret. ~ s(date1) + s(Diametro_copa_cm) + treatment , random=~(1|indv))
trend_areaves5 <- gamm4(data =area_porvaso_unido_DBH, area_Feret. ~ s(date1) + s(DBH_cm) +  s(Diametro_copa_cm) + treatment , random=~(1|indv))
trend_areaves6 <- gamm4(data =area_porvaso_unido_DBH, area_Feret. ~ s(date1) + s(DBH_cm) +  s(Diametro_copa_cm), random=~(1|indv))
trend_areaves7 <- gamm4(data =area_porvaso_unido_DBH, area_Feret. ~ s(date1) + s(DBH_cm) +  s(Diametro_copa_cm) + treatment , random=~(1|indv))

model.sel(trend_areaves1$mer, trend_areaves2$mer,trend_areaves3$mer, trend_areaves4$mer, trend_areaves5$mer, trend_areaves6$mer, trend_areaves7$mer) ###el mas significativo seria el 2

summary(trend_areaves1$gam)
summary(trend_areaves2$gam)
summary(trend_areaves3$gam)
summary(trend_areaves4$gam)
summary(trend_areaves5$gam)
summary(trend_areaves6$gam)
summary(trend_areaves7$gam)
sum(summary(trend_areaves1$gam)$s.table[, "edf"])
sum(summary(trend_areaves2$gam)$s.table[, "edf"])
sum(summary(trend_areaves3$gam)$s.table[, "edf"])
sum(summary(trend_areaves4$gam)$s.table[, "edf"])
sum(summary(trend_areaves5$gam)$s.table[, "edf"])
sum(summary(trend_areaves6$gam)$s.table[, "edf"])
sum(summary(trend_areaves7$gam)$s.table[, "edf"])

summary(trend_areaves$gam)
qqnorm(trend_areaves$gam$residuals)
qqline(trend_areaves$gam$residuals)



pred1 <- get_predictions(trend_areaves$gam, 
                       cond = list(date1 = seq(min(area_porvaso_unido$date1, na.rm=T),
                                            max(area_porvaso_unido$date1, na.rm=T), 
                                            length.out = nrow(area_porvaso_unido )),
                                  treatment = c("control", "drought"),
                                  se=T))

pred1$date <- as.Date(pred1$date1)

###calculo la tendencia pero en el acumulado


tendencia_area_vess <- ggplot(data=pred1)+
  geom_line(mapping = aes(x=date, y=fit, color= treatment), show.legend = F)+
  geom_ribbon(alpha=.4,mapping = aes(x=date, ymin=fit-CI, ymax=fit+CI, fill=treatment), show.legend = F) +
  geom_point(data = area_porvaso_unido, mapping =  aes(x=fecha, y=as.numeric(area_Feret.), fill =treatment), show.legend = F, shape = 21, size = 1.7, color = "black", stroke = 1)+
  scale_color_manual(values = c("#97FFFF","#FF6A6A"))+
  scale_fill_manual(values = c("#97FFFF","#FF6A6A"))+
  theme(panel.background = element_rect(fill = "white"),
          axis.line.x = element_line(colour="black"),
          axis.line.y = element_line(colour="black"),
        axis.text = element_text(color = "black",size = 12),
        axis.ticks.length  = unit(0.1, "cm"))+
  xlab("month")+
  ylab("area por vaso (mm^2)")
######me queda plotearlo y enviarlo


fila_inferior <- plot_grid(EW_areavessel, LW_areavessel, ncol = 2, rel_widths = c(1, 3))

combinado <- plot_grid(tendencia_area_vess, fila_inferior, ncol = 1, rel_heights = c(1, 1))


combinado

####ver si hay direncia entre tratamientos
area_anova <- split(area_porvaso_unido, area_porvaso_unido$fecha)
lapply(area_anova, function(x){summary(aov(data=x, area_Feret. ~ treatment))})



```

